"""step 26-e margin and short interest tables

Revision ID: 0487c98a0e37
Revises: c3f1f515e3df
Create Date: 2026-09-25

`margin_metrics` and `short_interest_metrics` (Step 26-e): legacy's margin and
SBL ratios and daily changes, each one wide row per (stock, source, date)
computed from that day's own input row. Derived, so no append-only trigger, and
the downgrade drops them without a guard: every row is recomputed from stored
inputs (CLAUDE.md §81).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0487c98a0e37'
down_revision: str | None = 'c3f1f515e3df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin_metrics',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('margin_usage_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('margin_balance_change', sa.BigInteger(), nullable=True),
    sa.Column('margin_balance_change_pct', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('short_usage_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('short_balance_change', sa.BigInteger(), nullable=True),
    sa.Column('short_balance_change_pct', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('short_cover_pressure', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_margin_metrics_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', name='pk_margin_metrics')
    )
    op.create_table('short_interest_metrics',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('sbl_balance_change', sa.BigInteger(), nullable=True),
    sa.Column('sbl_balance_change_pct', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('sbl_sell_repay_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_short_interest_metrics_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', name='pk_short_interest_metrics')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_interest_metrics')
    op.drop_table('margin_metrics')
    # ### end Alembic commands ###
