"""step 26-c cumulative flow table

Revision ID: 0f6386ea08db
Revises: 6ecc3eefb103
Create Date: 2026-09-24

`institutional_cumulative_flow` (Step 26-c): legacy's trust/dealer "holding" as
the zero-origin cumulative net flow it is, one wide row per (stock, source,
date). Derived, so no append-only trigger, and the downgrade drops it without a
guard: every row is recomputed from stored inputs (CLAUDE.md §81).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0f6386ea08db'
down_revision: str | None = '6ecc3eefb103'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_cumulative_flow',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trust_cumulative_net_shares', sa.BigInteger(), nullable=False),
    sa.Column('trust_cumulative_net_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('dealer_cumulative_net_shares', sa.BigInteger(), nullable=False),
    sa.Column('dealer_cumulative_net_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_institutional_cumulative_flow_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', name='pk_institutional_cumulative_flow')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institutional_cumulative_flow')
    # ### end Alembic commands ###
