"""add schema v2 foundation and exchange daily tables

Revision ID: 272951c4e3eb
Revises: d3b8c6f1a294
Create Date: 2026-09-23

ADR-0027. Creates the v2 tables beside the v1 ones: the foundation (`fetches`,
`stocks`, `trading_days`) and the exchange-published daily domains. v1 tables are
untouched here; each is dropped by the step that moves its domain across.

The value tables and the fetch log are append-only, enforced by the same
`stockdc_reject_mutation()` trigger function the v1 tables use.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '272951c4e3eb'
down_revision: str | None = 'd3b8c6f1a294'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY = (
    "fetches",
    "daily_prices",
    "index_prices",
    "valuations",
    "institutional_flows",
    "institutional_market_flows",
    "foreign_holdings",
    "margin_trading",
    "securities_lending",
)
ALL_TABLES = (*APPEND_ONLY, "stocks", "trading_days")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('resource_key', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('sha256', sa.LargeBinary(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("purpose IN ('first_capture', 'gap_fill', 'correction_check', 'unspecified')", name=op.f('ck_fetches_purpose_value')),
    sa.CheckConstraint("status <> 'succeeded' OR sha256 IS NOT NULL", name=op.f('ck_fetches_success_has_raw_file')),
    sa.CheckConstraint("status IN ('succeeded', 'empty', 'failed', 'quarantined')", name=op.f('ck_fetches_status_value')),
    sa.CheckConstraint('(sha256 IS NULL) = (byte_size IS NULL)', name=op.f('ck_fetches_raw_file_described')),
    sa.CheckConstraint('attempt > 0', name=op.f('ck_fetches_attempt_positive')),
    sa.CheckConstraint('sha256 IS NULL OR length(sha256) = 32', name=op.f('ck_fetches_sha256_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetches'))
    )
    op.create_index('ix_fetches_resource', 'fetches', ['dataset', 'source', 'resource_key', 'fetched_at'], unique=False)
    op.create_table('index_prices',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('index_name', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('open_value', sa.Numeric(), nullable=True),
    sa.Column('high_value', sa.Numeric(), nullable=True),
    sa.Column('low_value', sa.Numeric(), nullable=True),
    sa.Column('close_value', sa.Numeric(), nullable=True),
    sa.Column('change_points', sa.Numeric(), nullable=True),
    sa.Column('change_percent', sa.Numeric(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('change_percent IS NULL OR (scale(trim_scale(change_percent)) <= 2 AND abs(change_percent) < 1e6)', name=op.f('ck_index_prices_change_percent_precision')),
    sa.CheckConstraint('change_points IS NULL OR (scale(trim_scale(change_points)) <= 2 AND abs(change_points) < 1e10)', name=op.f('ck_index_prices_change_points_precision')),
    sa.CheckConstraint('close_value IS NULL OR (scale(trim_scale(close_value)) <= 2 AND abs(close_value) < 1e10)', name=op.f('ck_index_prices_close_value_precision')),
    sa.CheckConstraint('high_value IS NULL OR (scale(trim_scale(high_value)) <= 2 AND abs(high_value) < 1e10)', name=op.f('ck_index_prices_high_value_precision')),
    sa.CheckConstraint('low_value IS NULL OR (scale(trim_scale(low_value)) <= 2 AND abs(low_value) < 1e10)', name=op.f('ck_index_prices_low_value_precision')),
    sa.CheckConstraint('open_value IS NULL OR (scale(trim_scale(open_value)) <= 2 AND abs(open_value) < 1e10)', name=op.f('ck_index_prices_open_value_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_index_prices_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source', 'index_name', 'trade_date', 'recorded_at', name='pk_index_prices')
    )
    op.create_table('institutional_market_flows',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('buy', sa.BigInteger(), nullable=True),
    sa.Column('sell', sa.BigInteger(), nullable=True),
    sa.Column('net', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_institutional_market_flows_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source', 'trade_date', 'institution', 'recorded_at', name='pk_institutional_market_flows')
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('market', sa.String(length=3), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("btrim(stock_id) <> ''", name=op.f('ck_stocks_stock_id_nonempty')),
    sa.CheckConstraint("market IN ('sii', 'otc')", name=op.f('ck_stocks_market_value')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_stocks_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', name=op.f('pk_stocks'))
    )
    op.create_table('trading_days',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_trading_days_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trade_date', name=op.f('pk_trading_days'))
    )
    op.create_table('daily_prices',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=True),
    sa.Column('high_price', sa.Numeric(), nullable=True),
    sa.Column('low_price', sa.Numeric(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_value', sa.BigInteger(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('price_change', sa.Numeric(), nullable=True),
    sa.Column('price_direction', sa.String(length=4), nullable=True),
    sa.Column('last_bid_price', sa.Numeric(), nullable=True),
    sa.Column('last_ask_price', sa.Numeric(), nullable=True),
    sa.Column('last_bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('last_ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('close_price IS NULL OR (scale(trim_scale(close_price)) <= 2 AND abs(close_price) < 1e8)', name=op.f('ck_daily_prices_close_price_precision')),
    sa.CheckConstraint('high_price IS NULL OR (scale(trim_scale(high_price)) <= 2 AND abs(high_price) < 1e8)', name=op.f('ck_daily_prices_high_price_precision')),
    sa.CheckConstraint('last_ask_price IS NULL OR (scale(trim_scale(last_ask_price)) <= 2 AND abs(last_ask_price) < 1e8)', name=op.f('ck_daily_prices_last_ask_price_precision')),
    sa.CheckConstraint('last_ask_volume IS NULL OR last_ask_volume >= 0', name=op.f('ck_daily_prices_last_ask_volume_nonnegative')),
    sa.CheckConstraint('last_bid_price IS NULL OR (scale(trim_scale(last_bid_price)) <= 2 AND abs(last_bid_price) < 1e8)', name=op.f('ck_daily_prices_last_bid_price_precision')),
    sa.CheckConstraint('last_bid_volume IS NULL OR last_bid_volume >= 0', name=op.f('ck_daily_prices_last_bid_volume_nonnegative')),
    sa.CheckConstraint('low_price IS NULL OR (scale(trim_scale(low_price)) <= 2 AND abs(low_price) < 1e8)', name=op.f('ck_daily_prices_low_price_precision')),
    sa.CheckConstraint('open_price IS NULL OR (scale(trim_scale(open_price)) <= 2 AND abs(open_price) < 1e8)', name=op.f('ck_daily_prices_open_price_precision')),
    sa.CheckConstraint('price_change IS NULL OR (scale(trim_scale(price_change)) <= 2 AND abs(price_change) < 1e8)', name=op.f('ck_daily_prices_price_change_precision')),
    sa.CheckConstraint('trade_count IS NULL OR trade_count >= 0', name=op.f('ck_daily_prices_trade_count_nonnegative')),
    sa.CheckConstraint('trade_value IS NULL OR trade_value >= 0', name=op.f('ck_daily_prices_trade_value_nonnegative')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_daily_prices_volume_nonnegative')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_daily_prices_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_daily_prices_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_daily_prices')
    )
    op.create_table('foreign_holdings',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('issued_shares', sa.BigInteger(), nullable=True),
    sa.Column('investable_shares', sa.BigInteger(), nullable=True),
    sa.Column('held_shares', sa.BigInteger(), nullable=True),
    sa.Column('investable_ratio', sa.Numeric(), nullable=True),
    sa.Column('held_ratio', sa.Numeric(), nullable=True),
    sa.Column('foreign_legal_limit_ratio', sa.Numeric(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('foreign_legal_limit_ratio IS NULL OR (scale(trim_scale(foreign_legal_limit_ratio)) <= 2 AND abs(foreign_legal_limit_ratio) < 1e4)', name=op.f('ck_foreign_holdings_foreign_legal_limit_ratio_precision')),
    sa.CheckConstraint('held_ratio IS NULL OR (scale(trim_scale(held_ratio)) <= 2 AND abs(held_ratio) < 1e4)', name=op.f('ck_foreign_holdings_held_ratio_precision')),
    sa.CheckConstraint('investable_ratio IS NULL OR (scale(trim_scale(investable_ratio)) <= 2 AND abs(investable_ratio) < 1e4)', name=op.f('ck_foreign_holdings_investable_ratio_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_foreign_holdings_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_foreign_holdings_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_foreign_holdings')
    )
    op.create_table('institutional_flows',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('foreign_buy', sa.BigInteger(), nullable=True),
    sa.Column('foreign_sell', sa.BigInteger(), nullable=True),
    sa.Column('foreign_net', sa.BigInteger(), nullable=True),
    sa.Column('foreign_dealer_buy', sa.BigInteger(), nullable=True),
    sa.Column('foreign_dealer_sell', sa.BigInteger(), nullable=True),
    sa.Column('foreign_dealer_net', sa.BigInteger(), nullable=True),
    sa.Column('trust_buy', sa.BigInteger(), nullable=True),
    sa.Column('trust_sell', sa.BigInteger(), nullable=True),
    sa.Column('trust_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_buy', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_sell', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_buy', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_sell', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_net', sa.BigInteger(), nullable=True),
    sa.Column('total_net', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_institutional_flows_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_institutional_flows_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_institutional_flows')
    )
    op.create_table('margin_trading',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('margin_buy', sa.BigInteger(), nullable=True),
    sa.Column('margin_sell', sa.BigInteger(), nullable=True),
    sa.Column('margin_cash_repayment', sa.BigInteger(), nullable=True),
    sa.Column('margin_previous_balance', sa.BigInteger(), nullable=True),
    sa.Column('margin_balance', sa.BigInteger(), nullable=True),
    sa.Column('margin_limit', sa.BigInteger(), nullable=True),
    sa.Column('short_buy', sa.BigInteger(), nullable=True),
    sa.Column('short_sell', sa.BigInteger(), nullable=True),
    sa.Column('short_stock_repayment', sa.BigInteger(), nullable=True),
    sa.Column('short_previous_balance', sa.BigInteger(), nullable=True),
    sa.Column('short_balance', sa.BigInteger(), nullable=True),
    sa.Column('short_limit', sa.BigInteger(), nullable=True),
    sa.Column('offset_balance', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_margin_trading_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_margin_trading_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_margin_trading')
    )
    op.create_table('securities_lending',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('previous_balance', sa.BigInteger(), nullable=True),
    sa.Column('sold', sa.BigInteger(), nullable=True),
    sa.Column('returned', sa.BigInteger(), nullable=True),
    sa.Column('adjustment', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('next_limit', sa.BigInteger(), nullable=True),
    sa.Column('next_available_limit', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_securities_lending_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_securities_lending_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_securities_lending')
    )
    op.create_table('valuations',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('dividend_year', sa.SmallInteger(), nullable=True),
    sa.Column('report_period', sa.String(length=8), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('dividend_yield IS NULL OR (scale(trim_scale(dividend_yield)) <= 2 AND abs(dividend_yield) < 1e6)', name=op.f('ck_valuations_dividend_yield_precision')),
    sa.CheckConstraint('pb_ratio IS NULL OR (scale(trim_scale(pb_ratio)) <= 2 AND abs(pb_ratio) < 1e8)', name=op.f('ck_valuations_pb_ratio_precision')),
    sa.CheckConstraint('pe_ratio IS NULL OR (scale(trim_scale(pe_ratio)) <= 2 AND abs(pe_ratio) < 1e8)', name=op.f('ck_valuations_pe_ratio_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_valuations_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_valuations_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_valuations')
    )
    # ### end Alembic commands ###
    # Value tables and the fetch log are append-only.
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION stockdc_reject_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER no_truncate_{table} BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION stockdc_reject_mutation()"
        )


def downgrade() -> None:
    # Dropping these tables would discard stored history, so refuse before any
    # change if they hold a single row (CLAUDE.md §81).
    op.execute(
        "DO $$ DECLARE n bigint := 0; t text; BEGIN "
        "FOREACH t IN ARRAY ARRAY[" + ", ".join(f"'{t}'" for t in ALL_TABLES) + "] LOOP "
        "EXECUTE format('SELECT count(*) FROM (SELECT 1 FROM %I LIMIT 1) x', t) INTO n; "
        "IF n > 0 THEN RAISE EXCEPTION 'cannot downgrade: schema v2 table % holds rows', t; END IF; "
        "END LOOP; END $$"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuations')
    op.drop_table('securities_lending')
    op.drop_table('margin_trading')
    op.drop_table('institutional_flows')
    op.drop_table('foreign_holdings')
    op.drop_table('daily_prices')
    op.drop_table('trading_days')
    op.drop_table('stocks')
    op.drop_table('institutional_market_flows')
    op.drop_table('index_prices')
    op.drop_index('ix_fetches_resource', table_name='fetches')
    op.drop_table('fetches')
    # ### end Alembic commands ###
