"""step 26-f valuation metrics table

Revision ID: 31e69301ca35
Revises: 0487c98a0e37
Create Date: 2026-09-25

`valuation_metrics` (Step 26-f): TTM EPS, PE, PE percentile and ROE, one wide row
per (stock, price source, trade date), from the daily prices and the reports
public on that day. Derived, so no append-only trigger, and the downgrade drops
it without a guard: every row is recomputed from stored inputs (CLAUDE.md §81).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '31e69301ca35'
down_revision: str | None = '0487c98a0e37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuation_metrics',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ttm_eps', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('pe_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('pe_percentile', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('roe', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_valuation_metrics_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', name='pk_valuation_metrics')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_metrics')
    # ### end Alembic commands ###
