"""complete v1 storage contract

Revision ID: 58124040faa4
Revises: b7e1c9a42f10
Create Date: 2026-09-11 15:38:23.463262
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '58124040faa4'
down_revision: str | None = 'b7e1c9a42f10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add the complete v1 observed and canonical-derived storage contract.

    Cache impact: none. Phase 1 has no cache backend, this migration does not
    backdate temporal metadata, and no cached result namespace exists yet.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_index',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('index_code', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_index')),
    sa.UniqueConstraint('index_code', name=op.f('uq_market_index_index_code'))
    )
    op.create_table('derived_dataset_definitions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('derivation_version', sa.String(length=64), nullable=False),
    sa.Column('storage_strategy', sa.String(length=16), nullable=False),
    sa.Column('formula_specification', sa.Text(), nullable=False),
    sa.Column('implementation_version', sa.String(length=128), nullable=False),
    sa.Column('input_dataset_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calendar_timezone', sa.String(length=64), nullable=True),
    sa.Column('calendar_convention', sa.Text(), nullable=True),
    sa.Column('price_adjustment_convention', sa.Text(), nullable=True),
    sa.Column('definition_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("jsonb_typeof(input_dataset_codes) = 'array'", name=op.f('ck_derived_dataset_definitions_input_datasets_array')),
    sa.CheckConstraint("storage_strategy IN ('materialized', 'virtual')", name=op.f('ck_derived_dataset_definitions_storage_strategy_value')),
    sa.ForeignKeyConstraint(['dataset_code'], ['dataset_catalog.dataset_code'], name=op.f('fk_derived_dataset_definitions_dataset_code_dataset_catalog'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derived_dataset_definitions')),
    sa.UniqueConstraint('dataset_code', 'derivation_version', name='uq_derived_definition_version')
    )
    op.create_table('derived_computation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('definition_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('implementation_version', sa.String(length=128), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f('ck_derived_computation_runs_status_value')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_derived_computation_runs_completed_after_started')),
    sa.ForeignKeyConstraint(['definition_id'], ['derived_dataset_definitions.id'], name=op.f('fk_derived_computation_runs_definition_id_derived_dataset_definitions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derived_computation_runs'))
    )
    op.create_table('derived_metric_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('definition_id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('metric_code', sa.String(length=128), nullable=False),
    sa.Column('pit_mode', sa.String(length=16), nullable=False),
    sa.Column('information_as_of', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('knowledge_as_of', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('system_as_of', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('input_dataset_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_fingerprint', sa.CHAR(length=64), nullable=False),
    sa.Column('computation_run_id', sa.UUID(), nullable=False),
    sa.Column('numeric_value', sa.Numeric(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('json_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("(pit_mode = 'market' AND information_as_of IS NOT NULL AND knowledge_as_of IS NOT NULL AND system_as_of IS NULL) OR (pit_mode = 'system' AND information_as_of IS NULL AND knowledge_as_of IS NULL AND system_as_of IS NOT NULL)", name=op.f('ck_derived_metric_versions_pit_context_shape')),
    sa.CheckConstraint("input_fingerprint ~ '^[0-9a-f]{64}$'", name=op.f('ck_derived_metric_versions_input_fingerprint_lower_hex')),
    sa.CheckConstraint('num_nonnulls(numeric_value, text_value, json_value) = 1', name=op.f('ck_derived_metric_versions_one_value')),
    sa.ForeignKeyConstraint(['computation_run_id'], ['derived_computation_runs.id'], name=op.f('fk_derived_metric_versions_computation_run_id_derived_computation_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['definition_id'], ['derived_dataset_definitions.id'], name=op.f('fk_derived_metric_versions_definition_id_derived_dataset_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_derived_metric_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derived_metric_versions'))
    )
    op.create_index('uq_derived_metric_semantic_identity', 'derived_metric_versions', ['definition_id', 'security_id', 'observation_date', 'metric_code', 'pit_mode', 'information_as_of', 'knowledge_as_of', 'system_as_of', 'input_fingerprint'], unique=True, postgresql_nulls_not_distinct=True)
    op.create_table('corporate_action_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('cash_dividend_per_share', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('stock_dividend_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('rights_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('subscription_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close_before', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('rights_dividend_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action_type IN ('cash_dividend', 'stock_dividend', 'rights', 'ex_dividend', 'ex_right', 'capital_reduction', 'other')", name=op.f('ck_corporate_action_versions_action_type_value')),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_corporate_action_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_corporate_action_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_action_versions')),
    sa.UniqueConstraint('security_id', 'source', 'action_type', 'ex_date', 'business_content_hash', name='uq_corporate_action_business_revision')
    )
    op.create_table('foreign_holding_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('issued_shares', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('investable_shares', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('held_shares', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('investable_ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('held_ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('foreign_legal_limit_ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('mainland_legal_limit_ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('source_last_update_date', sa.Date(), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_foreign_holding_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_foreign_holding_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foreign_holding_versions')),
    sa.UniqueConstraint('security_id', 'source', 'trade_date', 'business_content_hash', name='uq_foreign_holding_business_revision')
    )
    op.create_table('institutional_investor_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('foreign_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('foreign_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('foreign_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('foreign_dealer_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('foreign_dealer_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('foreign_dealer_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('trust_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('trust_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('trust_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_self_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_self_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_self_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_hedge_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_hedge_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_hedge_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('dealer_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_institutional_investor_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_institutional_investor_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutional_investor_versions')),
    sa.UniqueConstraint('security_id', 'source', 'trade_date', 'business_content_hash', name='uq_institutional_investor_business_revision')
    )
    op.create_table('institutional_market_summary_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=False),
    sa.Column('buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('net', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_institutional_market_summary_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutional_market_summary_versions')),
    sa.UniqueConstraint('market', 'source', 'trade_date', 'institution', 'business_content_hash', name='uq_institutional_summary_business_revision')
    )
    op.create_table('margin_trading_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('margin_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('margin_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('margin_cash_repayment', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('margin_previous_balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('margin_balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('margin_next_limit', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('margin_utilization_ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('short_buy', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('short_sell', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('short_stock_repayment', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('short_previous_balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('short_balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('short_next_limit', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('short_utilization_ratio', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('offset_balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_margin_trading_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_margin_trading_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_margin_trading_versions')),
    sa.UniqueConstraint('security_id', 'source', 'trade_date', 'business_content_hash', name='uq_margin_trading_business_revision')
    )
    op.create_table('market_index_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('market_index_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('high_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('low_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('close_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('change_points', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('trade_value', sa.Numeric(precision=30, scale=4), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['market_index_id'], ['market_index.id'], name=op.f('fk_market_index_versions_market_index_id_market_index'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_market_index_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_index_versions')),
    sa.UniqueConstraint('market_index_id', 'source', 'trade_date', 'business_content_hash', name='uq_market_index_business_revision')
    )
    op.create_table('official_valuation_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('dividend_year', sa.SmallInteger(), nullable=True),
    sa.Column('dividend_per_share', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('report_period', sa.String(length=16), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_official_valuation_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_official_valuation_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_official_valuation_versions')),
    sa.UniqueConstraint('security_id', 'source', 'trade_date', 'business_content_hash', name='uq_official_valuation_business_revision')
    )
    op.create_table('securities_lending_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('previous_balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('borrowed', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('returned', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('balance', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('next_limit', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('next_available_limit', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('adjustment', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_securities_lending_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_securities_lending_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities_lending_versions')),
    sa.UniqueConstraint('security_id', 'source', 'trade_date', 'business_content_hash', name='uq_securities_lending_business_revision')
    )
    op.create_table('security_tag_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_security_tag_versions_effective_range')),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_security_tag_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_security_tag_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_tag_versions')),
    sa.UniqueConstraint('security_id', 'source', 'tag', 'effective_from', 'business_content_hash', name='uq_security_tag_business_revision')
    )
    op.create_table('xbrl_concept_catalog_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('concept_qname', sa.Text(), nullable=False),
    sa.Column('statement_type', sa.String(length=32), nullable=False),
    sa.Column('account_name_zh', sa.Text(), nullable=True),
    sa.Column('account_name_en', sa.Text(), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_xbrl_concept_catalog_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xbrl_concept_catalog_versions')),
    sa.UniqueConstraint('source', 'concept_qname', 'business_content_hash', name='uq_xbrl_concept_business_revision')
    )
    op.add_column('daily_price_versions', sa.Column('trade_value', sa.Numeric(precision=30, scale=4), nullable=True))
    op.add_column('daily_price_versions', sa.Column('trade_count', sa.BigInteger(), nullable=True))
    op.add_column('daily_price_versions', sa.Column('price_change', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('daily_price_versions', sa.Column('price_direction', sa.String(length=16), nullable=True))
    op.add_column('daily_price_versions', sa.Column('bid_snapshot', sa.Text(), nullable=True))
    op.add_column('daily_price_versions', sa.Column('ask_snapshot', sa.Text(), nullable=True))
    op.add_column('daily_price_versions', sa.Column('last_bid_price', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('daily_price_versions', sa.Column('last_ask_price', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('daily_price_versions', sa.Column('last_bid_volume', sa.Numeric(precision=30, scale=0), nullable=True))
    op.add_column('daily_price_versions', sa.Column('last_ask_volume', sa.Numeric(precision=30, scale=0), nullable=True))
    op.create_check_constraint(
        op.f('ck_daily_price_versions_trade_value_nonnegative'),
        'daily_price_versions',
        'trade_value IS NULL OR trade_value >= 0',
    )
    op.create_check_constraint(
        op.f('ck_daily_price_versions_trade_count_nonnegative'),
        'daily_price_versions',
        'trade_count IS NULL OR trade_count >= 0',
    )
    op.add_column('publication_evidence', sa.Column('institutional_investor_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('foreign_holding_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('institutional_market_summary_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('margin_trading_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('securities_lending_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('market_index_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('corporate_action_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('official_valuation_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('security_tag_version_id', sa.BigInteger(), nullable=True))
    op.add_column('publication_evidence', sa.Column('xbrl_concept_catalog_version_id', sa.BigInteger(), nullable=True))
    op.drop_constraint(
        op.f('ck_publication_evidence_exactly_one_target'),
        'publication_evidence',
        type_='check',
    )
    op.create_check_constraint(
        op.f('ck_publication_evidence_exactly_one_target'),
        'publication_evidence',
        '''num_nonnulls(
            security_metadata_version_id,
            daily_price_version_id,
            monthly_revenue_version_id,
            financial_filing_version_id,
            tdcc_snapshot_version_id,
            institutional_investor_version_id,
            foreign_holding_version_id,
            institutional_market_summary_version_id,
            margin_trading_version_id,
            securities_lending_version_id,
            market_index_version_id,
            corporate_action_version_id,
            official_valuation_version_id,
            security_tag_version_id,
            xbrl_concept_catalog_version_id
        ) = 1''',
    )
    op.create_foreign_key(op.f('fk_publication_evidence_official_valuation_version_id_official_valuation_versions'), 'publication_evidence', 'official_valuation_versions', ['official_valuation_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_corporate_action_version_id_corporate_action_versions'), 'publication_evidence', 'corporate_action_versions', ['corporate_action_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_xbrl_concept_catalog_version_id_xbrl_concept_catalog_versions'), 'publication_evidence', 'xbrl_concept_catalog_versions', ['xbrl_concept_catalog_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_institutional_investor_version_id_institutional_investor_versions'), 'publication_evidence', 'institutional_investor_versions', ['institutional_investor_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_institutional_market_summary_version_id_institutional_market_summary_versions'), 'publication_evidence', 'institutional_market_summary_versions', ['institutional_market_summary_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_securities_lending_version_id_securities_lending_versions'), 'publication_evidence', 'securities_lending_versions', ['securities_lending_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_security_tag_version_id_security_tag_versions'), 'publication_evidence', 'security_tag_versions', ['security_tag_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_margin_trading_version_id_margin_trading_versions'), 'publication_evidence', 'margin_trading_versions', ['margin_trading_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_foreign_holding_version_id_foreign_holding_versions'), 'publication_evidence', 'foreign_holding_versions', ['foreign_holding_version_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_publication_evidence_market_index_version_id_market_index_versions'), 'publication_evidence', 'market_index_versions', ['market_index_version_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('ck_publication_evidence_exactly_one_target'),
        'publication_evidence',
        type_='check',
    )
    op.drop_constraint(op.f('fk_publication_evidence_market_index_version_id_market_index_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_foreign_holding_version_id_foreign_holding_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_margin_trading_version_id_margin_trading_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_security_tag_version_id_security_tag_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_securities_lending_version_id_securities_lending_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_institutional_market_summary_version_id_institutional_market_summary_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_institutional_investor_version_id_institutional_investor_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_xbrl_concept_catalog_version_id_xbrl_concept_catalog_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_corporate_action_version_id_corporate_action_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_constraint(op.f('fk_publication_evidence_official_valuation_version_id_official_valuation_versions'), 'publication_evidence', type_='foreignkey')
    op.drop_column('publication_evidence', 'xbrl_concept_catalog_version_id')
    op.drop_column('publication_evidence', 'security_tag_version_id')
    op.drop_column('publication_evidence', 'official_valuation_version_id')
    op.drop_column('publication_evidence', 'corporate_action_version_id')
    op.drop_column('publication_evidence', 'market_index_version_id')
    op.drop_column('publication_evidence', 'securities_lending_version_id')
    op.drop_column('publication_evidence', 'margin_trading_version_id')
    op.drop_column('publication_evidence', 'institutional_market_summary_version_id')
    op.drop_column('publication_evidence', 'foreign_holding_version_id')
    op.drop_column('publication_evidence', 'institutional_investor_version_id')
    op.create_check_constraint(
        op.f('ck_publication_evidence_exactly_one_target'),
        'publication_evidence',
        '''num_nonnulls(
            security_metadata_version_id,
            daily_price_version_id,
            monthly_revenue_version_id,
            financial_filing_version_id,
            tdcc_snapshot_version_id
        ) = 1''',
    )
    op.drop_constraint(
        op.f('ck_daily_price_versions_trade_count_nonnegative'),
        'daily_price_versions',
        type_='check',
    )
    op.drop_constraint(
        op.f('ck_daily_price_versions_trade_value_nonnegative'),
        'daily_price_versions',
        type_='check',
    )
    op.drop_column('daily_price_versions', 'last_ask_volume')
    op.drop_column('daily_price_versions', 'last_bid_volume')
    op.drop_column('daily_price_versions', 'last_ask_price')
    op.drop_column('daily_price_versions', 'last_bid_price')
    op.drop_column('daily_price_versions', 'ask_snapshot')
    op.drop_column('daily_price_versions', 'bid_snapshot')
    op.drop_column('daily_price_versions', 'price_direction')
    op.drop_column('daily_price_versions', 'price_change')
    op.drop_column('daily_price_versions', 'trade_count')
    op.drop_column('daily_price_versions', 'trade_value')
    op.drop_table('xbrl_concept_catalog_versions')
    op.drop_table('security_tag_versions')
    op.drop_table('securities_lending_versions')
    op.drop_table('official_valuation_versions')
    op.drop_table('market_index_versions')
    op.drop_table('margin_trading_versions')
    op.drop_table('institutional_market_summary_versions')
    op.drop_table('institutional_investor_versions')
    op.drop_table('foreign_holding_versions')
    op.drop_table('corporate_action_versions')
    op.drop_index('uq_derived_metric_semantic_identity', table_name='derived_metric_versions', postgresql_nulls_not_distinct=True)
    op.drop_table('derived_metric_versions')
    op.drop_table('derived_computation_runs')
    op.drop_table('derived_dataset_definitions')
    op.drop_table('market_index')
    # ### end Alembic commands ###
