"""step 26-b derived tables

Revision ID: 6ecc3eefb103
Revises: a273160c0288
Create Date: 2026-09-24

The first stored derived tables (ROADMAP §17, Step 26-b): `technical_indicators`
and `institutional_streaks`, one wide row per (stock, source, date). They are
computed from the latest inputs and overwritten in place, so they carry no
append-only trigger. Every row is recomputed from stored inputs, so the
downgrade drops them without a guard: nothing it discards is history
(CLAUDE.md §81).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6ecc3eefb103'
down_revision: str | None = 'a273160c0288'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_streaks',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('foreign_streak_days', sa.Integer(), nullable=False),
    sa.Column('trust_streak_days', sa.Integer(), nullable=False),
    sa.Column('dealer_streak_days', sa.Integer(), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_institutional_streaks_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', name='pk_institutional_streaks')
    )
    op.create_table('technical_indicators',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('ma10', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('ma20', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('ma60', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('ma120', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('ma240', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('vma5', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('vma10', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('vma20', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('vma60', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('vma120', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('vma240', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('k', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('d', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('rsi6', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('rsi12', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('macd_dif', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('macd_dea', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('macd_hist', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('bb_upper', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('bb_middle', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('bb_lower', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_technical_indicators_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', name='pk_technical_indicators')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_indicators')
    op.drop_table('institutional_streaks')
    # ### end Alembic commands ###
