"""add schema v2 issuer and tdcc tables

Revision ID: 76245e1b428b
Revises: 272951c4e3eb
Create Date: 2026-09-23

ADR-0027 "35-c 定案", Step 35-c-1: monthly revenue, financial reports and
their facts, TDCC shareholding distributions and corporate actions. The v1
tables of these domains are untouched; 35-d drops every v1 table at once.
All five are append-only, like the other v2 value tables.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '76245e1b428b'
down_revision: str | None = '272951c4e3eb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = (
    "monthly_revenues",
    "financial_reports",
    "financial_report_facts",
    "shareholding_distributions",
    "corporate_actions",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('close_before', sa.Numeric(), nullable=True),
    sa.Column('reference_price', sa.Numeric(), nullable=True),
    sa.Column('rights_dividend_value', sa.Numeric(), nullable=True),
    sa.Column('cash_dividend_per_share', sa.Numeric(), nullable=True),
    sa.Column('free_share_ratio', sa.Numeric(), nullable=True),
    sa.Column('rights_ratio', sa.Numeric(), nullable=True),
    sa.Column('subscription_price', sa.Numeric(), nullable=True),
    sa.Column('old_shares', sa.Numeric(), nullable=True),
    sa.Column('new_shares', sa.Numeric(), nullable=True),
    sa.Column('cash_return_per_share', sa.Numeric(), nullable=True),
    sa.Column('retracted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("event_type <> ''", name=op.f('ck_corporate_actions_event_type_nonempty')),
    sa.CheckConstraint('(old_shares IS NULL) = (new_shares IS NULL)', name=op.f('ck_corporate_actions_share_pair')),
    sa.CheckConstraint('cash_dividend_per_share IS NULL OR (scale(trim_scale(cash_dividend_per_share)) <= 8 AND abs(cash_dividend_per_share) < 1e4)', name=op.f('ck_corporate_actions_cash_dividend_per_share_precision')),
    sa.CheckConstraint('cash_dividend_per_share IS NULL OR cash_dividend_per_share >= 0', name=op.f('ck_corporate_actions_cash_dividend_per_share_nonnegative')),
    sa.CheckConstraint('cash_return_per_share IS NULL OR (scale(trim_scale(cash_return_per_share)) <= 8 AND abs(cash_return_per_share) < 1e4)', name=op.f('ck_corporate_actions_cash_return_per_share_precision')),
    sa.CheckConstraint('cash_return_per_share IS NULL OR cash_return_per_share >= 0', name=op.f('ck_corporate_actions_cash_return_per_share_nonnegative')),
    sa.CheckConstraint('close_before IS NULL OR (scale(trim_scale(close_before)) <= 2 AND abs(close_before) < 1e8)', name=op.f('ck_corporate_actions_close_before_precision')),
    sa.CheckConstraint('close_before IS NULL OR close_before >= 0', name=op.f('ck_corporate_actions_close_before_nonnegative')),
    sa.CheckConstraint('free_share_ratio IS NULL OR (scale(trim_scale(free_share_ratio)) <= 12 AND abs(free_share_ratio) < 1e2)', name=op.f('ck_corporate_actions_free_share_ratio_precision')),
    sa.CheckConstraint('free_share_ratio IS NULL OR free_share_ratio >= 0', name=op.f('ck_corporate_actions_free_share_ratio_nonnegative')),
    sa.CheckConstraint('new_shares IS NULL OR (scale(trim_scale(new_shares)) <= 8 AND abs(new_shares) < 1e5)', name=op.f('ck_corporate_actions_new_shares_precision')),
    sa.CheckConstraint('new_shares IS NULL OR new_shares >= 0', name=op.f('ck_corporate_actions_new_shares_nonnegative')),
    sa.CheckConstraint('old_shares IS NULL OR (scale(trim_scale(old_shares)) <= 8 AND abs(old_shares) < 1e5)', name=op.f('ck_corporate_actions_old_shares_precision')),
    sa.CheckConstraint('old_shares IS NULL OR old_shares >= 0', name=op.f('ck_corporate_actions_old_shares_nonnegative')),
    sa.CheckConstraint('reference_price IS NULL OR (scale(trim_scale(reference_price)) <= 2 AND abs(reference_price) < 1e8)', name=op.f('ck_corporate_actions_reference_price_precision')),
    sa.CheckConstraint('reference_price IS NULL OR reference_price >= 0', name=op.f('ck_corporate_actions_reference_price_nonnegative')),
    sa.CheckConstraint('rights_dividend_value IS NULL OR (scale(trim_scale(rights_dividend_value)) <= 6 AND abs(rights_dividend_value) < 1e8)', name=op.f('ck_corporate_actions_rights_dividend_value_precision')),
    sa.CheckConstraint('rights_ratio IS NULL OR (scale(trim_scale(rights_ratio)) <= 12 AND abs(rights_ratio) < 1e2)', name=op.f('ck_corporate_actions_rights_ratio_precision')),
    sa.CheckConstraint('rights_ratio IS NULL OR rights_ratio >= 0', name=op.f('ck_corporate_actions_rights_ratio_nonnegative')),
    sa.CheckConstraint('subscription_price IS NULL OR (scale(trim_scale(subscription_price)) <= 2 AND abs(subscription_price) < 1e8)', name=op.f('ck_corporate_actions_subscription_price_precision')),
    sa.CheckConstraint('subscription_price IS NULL OR subscription_price >= 0', name=op.f('ck_corporate_actions_subscription_price_nonnegative')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_corporate_actions_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_corporate_actions_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'ex_date', 'recorded_at', name='pk_corporate_actions')
    )
    op.create_table('financial_reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('report_year', sa.SmallInteger(), nullable=False),
    sa.Column('report_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('report_category', sa.String(length=12), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("report_category IN ('consolidated', 'individual')", name=op.f('ck_financial_reports_report_category_value')),
    sa.CheckConstraint('report_quarter BETWEEN 1 AND 4', name=op.f('ck_financial_reports_report_quarter_range')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_financial_reports_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_financial_reports_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_reports')),
    sa.UniqueConstraint('stock_id', 'report_year', 'report_quarter', 'recorded_at', name='uq_financial_reports_version')
    )
    op.create_table('monthly_revenues',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('revenue_month', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=False),
    sa.Column('revenue_last_month', sa.BigInteger(), nullable=True),
    sa.Column('revenue_last_year_month', sa.BigInteger(), nullable=True),
    sa.Column('cumulative_revenue', sa.BigInteger(), nullable=True),
    sa.Column('cumulative_revenue_last_year', sa.BigInteger(), nullable=True),
    sa.Column('mom_pct', sa.Numeric(), nullable=True),
    sa.Column('yoy_pct', sa.Numeric(), nullable=True),
    sa.Column('cumulative_yoy_pct', sa.Numeric(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("revenue_month = date_trunc('month', revenue_month)::date", name=op.f('ck_monthly_revenues_revenue_month_first_day')),
    sa.CheckConstraint('cumulative_yoy_pct IS NULL OR (scale(trim_scale(cumulative_yoy_pct)) <= 2 AND abs(cumulative_yoy_pct) < 1e8)', name=op.f('ck_monthly_revenues_cumulative_yoy_pct_precision')),
    sa.CheckConstraint('mom_pct IS NULL OR (scale(trim_scale(mom_pct)) <= 2 AND abs(mom_pct) < 1e8)', name=op.f('ck_monthly_revenues_mom_pct_precision')),
    sa.CheckConstraint('yoy_pct IS NULL OR (scale(trim_scale(yoy_pct)) <= 2 AND abs(yoy_pct) < 1e8)', name=op.f('ck_monthly_revenues_yoy_pct_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_monthly_revenues_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_monthly_revenues_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'revenue_month', 'recorded_at', name='pk_monthly_revenues')
    )
    op.create_table('shareholding_distributions',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('holders_1', sa.BigInteger(), nullable=True),
    sa.Column('shares_1', sa.BigInteger(), nullable=True),
    sa.Column('percent_1', sa.Numeric(), nullable=True),
    sa.Column('holders_2', sa.BigInteger(), nullable=True),
    sa.Column('shares_2', sa.BigInteger(), nullable=True),
    sa.Column('percent_2', sa.Numeric(), nullable=True),
    sa.Column('holders_3', sa.BigInteger(), nullable=True),
    sa.Column('shares_3', sa.BigInteger(), nullable=True),
    sa.Column('percent_3', sa.Numeric(), nullable=True),
    sa.Column('holders_4', sa.BigInteger(), nullable=True),
    sa.Column('shares_4', sa.BigInteger(), nullable=True),
    sa.Column('percent_4', sa.Numeric(), nullable=True),
    sa.Column('holders_5', sa.BigInteger(), nullable=True),
    sa.Column('shares_5', sa.BigInteger(), nullable=True),
    sa.Column('percent_5', sa.Numeric(), nullable=True),
    sa.Column('holders_6', sa.BigInteger(), nullable=True),
    sa.Column('shares_6', sa.BigInteger(), nullable=True),
    sa.Column('percent_6', sa.Numeric(), nullable=True),
    sa.Column('holders_7', sa.BigInteger(), nullable=True),
    sa.Column('shares_7', sa.BigInteger(), nullable=True),
    sa.Column('percent_7', sa.Numeric(), nullable=True),
    sa.Column('holders_8', sa.BigInteger(), nullable=True),
    sa.Column('shares_8', sa.BigInteger(), nullable=True),
    sa.Column('percent_8', sa.Numeric(), nullable=True),
    sa.Column('holders_9', sa.BigInteger(), nullable=True),
    sa.Column('shares_9', sa.BigInteger(), nullable=True),
    sa.Column('percent_9', sa.Numeric(), nullable=True),
    sa.Column('holders_10', sa.BigInteger(), nullable=True),
    sa.Column('shares_10', sa.BigInteger(), nullable=True),
    sa.Column('percent_10', sa.Numeric(), nullable=True),
    sa.Column('holders_11', sa.BigInteger(), nullable=True),
    sa.Column('shares_11', sa.BigInteger(), nullable=True),
    sa.Column('percent_11', sa.Numeric(), nullable=True),
    sa.Column('holders_12', sa.BigInteger(), nullable=True),
    sa.Column('shares_12', sa.BigInteger(), nullable=True),
    sa.Column('percent_12', sa.Numeric(), nullable=True),
    sa.Column('holders_13', sa.BigInteger(), nullable=True),
    sa.Column('shares_13', sa.BigInteger(), nullable=True),
    sa.Column('percent_13', sa.Numeric(), nullable=True),
    sa.Column('holders_14', sa.BigInteger(), nullable=True),
    sa.Column('shares_14', sa.BigInteger(), nullable=True),
    sa.Column('percent_14', sa.Numeric(), nullable=True),
    sa.Column('holders_15', sa.BigInteger(), nullable=True),
    sa.Column('shares_15', sa.BigInteger(), nullable=True),
    sa.Column('percent_15', sa.Numeric(), nullable=True),
    sa.Column('adjustment_shares', sa.BigInteger(), nullable=True),
    sa.Column('adjustment_percent', sa.Numeric(), nullable=True),
    sa.Column('total_holders', sa.BigInteger(), nullable=True),
    sa.Column('total_shares', sa.BigInteger(), nullable=True),
    sa.Column('total_percent', sa.Numeric(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('adjustment_percent IS NULL OR (scale(trim_scale(adjustment_percent)) <= 2 AND abs(adjustment_percent) < 1e3)', name=op.f('ck_shareholding_distributions_adjustment_percent_precision')),
    sa.CheckConstraint('holders_1 IS NULL OR holders_1 >= 0', name=op.f('ck_shareholding_distributions_holders_1_nonnegative')),
    sa.CheckConstraint('holders_10 IS NULL OR holders_10 >= 0', name=op.f('ck_shareholding_distributions_holders_10_nonnegative')),
    sa.CheckConstraint('holders_11 IS NULL OR holders_11 >= 0', name=op.f('ck_shareholding_distributions_holders_11_nonnegative')),
    sa.CheckConstraint('holders_12 IS NULL OR holders_12 >= 0', name=op.f('ck_shareholding_distributions_holders_12_nonnegative')),
    sa.CheckConstraint('holders_13 IS NULL OR holders_13 >= 0', name=op.f('ck_shareholding_distributions_holders_13_nonnegative')),
    sa.CheckConstraint('holders_14 IS NULL OR holders_14 >= 0', name=op.f('ck_shareholding_distributions_holders_14_nonnegative')),
    sa.CheckConstraint('holders_15 IS NULL OR holders_15 >= 0', name=op.f('ck_shareholding_distributions_holders_15_nonnegative')),
    sa.CheckConstraint('holders_2 IS NULL OR holders_2 >= 0', name=op.f('ck_shareholding_distributions_holders_2_nonnegative')),
    sa.CheckConstraint('holders_3 IS NULL OR holders_3 >= 0', name=op.f('ck_shareholding_distributions_holders_3_nonnegative')),
    sa.CheckConstraint('holders_4 IS NULL OR holders_4 >= 0', name=op.f('ck_shareholding_distributions_holders_4_nonnegative')),
    sa.CheckConstraint('holders_5 IS NULL OR holders_5 >= 0', name=op.f('ck_shareholding_distributions_holders_5_nonnegative')),
    sa.CheckConstraint('holders_6 IS NULL OR holders_6 >= 0', name=op.f('ck_shareholding_distributions_holders_6_nonnegative')),
    sa.CheckConstraint('holders_7 IS NULL OR holders_7 >= 0', name=op.f('ck_shareholding_distributions_holders_7_nonnegative')),
    sa.CheckConstraint('holders_8 IS NULL OR holders_8 >= 0', name=op.f('ck_shareholding_distributions_holders_8_nonnegative')),
    sa.CheckConstraint('holders_9 IS NULL OR holders_9 >= 0', name=op.f('ck_shareholding_distributions_holders_9_nonnegative')),
    sa.CheckConstraint('percent_1 IS NULL OR (scale(trim_scale(percent_1)) <= 2 AND abs(percent_1) < 1e3)', name=op.f('ck_shareholding_distributions_percent_1_precision')),
    sa.CheckConstraint('percent_10 IS NULL OR (scale(trim_scale(percent_10)) <= 2 AND abs(percent_10) < 1e3)', name=op.f('ck_shareholding_distributions_percent_10_precision')),
    sa.CheckConstraint('percent_11 IS NULL OR (scale(trim_scale(percent_11)) <= 2 AND abs(percent_11) < 1e3)', name=op.f('ck_shareholding_distributions_percent_11_precision')),
    sa.CheckConstraint('percent_12 IS NULL OR (scale(trim_scale(percent_12)) <= 2 AND abs(percent_12) < 1e3)', name=op.f('ck_shareholding_distributions_percent_12_precision')),
    sa.CheckConstraint('percent_13 IS NULL OR (scale(trim_scale(percent_13)) <= 2 AND abs(percent_13) < 1e3)', name=op.f('ck_shareholding_distributions_percent_13_precision')),
    sa.CheckConstraint('percent_14 IS NULL OR (scale(trim_scale(percent_14)) <= 2 AND abs(percent_14) < 1e3)', name=op.f('ck_shareholding_distributions_percent_14_precision')),
    sa.CheckConstraint('percent_15 IS NULL OR (scale(trim_scale(percent_15)) <= 2 AND abs(percent_15) < 1e3)', name=op.f('ck_shareholding_distributions_percent_15_precision')),
    sa.CheckConstraint('percent_2 IS NULL OR (scale(trim_scale(percent_2)) <= 2 AND abs(percent_2) < 1e3)', name=op.f('ck_shareholding_distributions_percent_2_precision')),
    sa.CheckConstraint('percent_3 IS NULL OR (scale(trim_scale(percent_3)) <= 2 AND abs(percent_3) < 1e3)', name=op.f('ck_shareholding_distributions_percent_3_precision')),
    sa.CheckConstraint('percent_4 IS NULL OR (scale(trim_scale(percent_4)) <= 2 AND abs(percent_4) < 1e3)', name=op.f('ck_shareholding_distributions_percent_4_precision')),
    sa.CheckConstraint('percent_5 IS NULL OR (scale(trim_scale(percent_5)) <= 2 AND abs(percent_5) < 1e3)', name=op.f('ck_shareholding_distributions_percent_5_precision')),
    sa.CheckConstraint('percent_6 IS NULL OR (scale(trim_scale(percent_6)) <= 2 AND abs(percent_6) < 1e3)', name=op.f('ck_shareholding_distributions_percent_6_precision')),
    sa.CheckConstraint('percent_7 IS NULL OR (scale(trim_scale(percent_7)) <= 2 AND abs(percent_7) < 1e3)', name=op.f('ck_shareholding_distributions_percent_7_precision')),
    sa.CheckConstraint('percent_8 IS NULL OR (scale(trim_scale(percent_8)) <= 2 AND abs(percent_8) < 1e3)', name=op.f('ck_shareholding_distributions_percent_8_precision')),
    sa.CheckConstraint('percent_9 IS NULL OR (scale(trim_scale(percent_9)) <= 2 AND abs(percent_9) < 1e3)', name=op.f('ck_shareholding_distributions_percent_9_precision')),
    sa.CheckConstraint('shares_1 IS NULL OR shares_1 >= 0', name=op.f('ck_shareholding_distributions_shares_1_nonnegative')),
    sa.CheckConstraint('shares_10 IS NULL OR shares_10 >= 0', name=op.f('ck_shareholding_distributions_shares_10_nonnegative')),
    sa.CheckConstraint('shares_11 IS NULL OR shares_11 >= 0', name=op.f('ck_shareholding_distributions_shares_11_nonnegative')),
    sa.CheckConstraint('shares_12 IS NULL OR shares_12 >= 0', name=op.f('ck_shareholding_distributions_shares_12_nonnegative')),
    sa.CheckConstraint('shares_13 IS NULL OR shares_13 >= 0', name=op.f('ck_shareholding_distributions_shares_13_nonnegative')),
    sa.CheckConstraint('shares_14 IS NULL OR shares_14 >= 0', name=op.f('ck_shareholding_distributions_shares_14_nonnegative')),
    sa.CheckConstraint('shares_15 IS NULL OR shares_15 >= 0', name=op.f('ck_shareholding_distributions_shares_15_nonnegative')),
    sa.CheckConstraint('shares_2 IS NULL OR shares_2 >= 0', name=op.f('ck_shareholding_distributions_shares_2_nonnegative')),
    sa.CheckConstraint('shares_3 IS NULL OR shares_3 >= 0', name=op.f('ck_shareholding_distributions_shares_3_nonnegative')),
    sa.CheckConstraint('shares_4 IS NULL OR shares_4 >= 0', name=op.f('ck_shareholding_distributions_shares_4_nonnegative')),
    sa.CheckConstraint('shares_5 IS NULL OR shares_5 >= 0', name=op.f('ck_shareholding_distributions_shares_5_nonnegative')),
    sa.CheckConstraint('shares_6 IS NULL OR shares_6 >= 0', name=op.f('ck_shareholding_distributions_shares_6_nonnegative')),
    sa.CheckConstraint('shares_7 IS NULL OR shares_7 >= 0', name=op.f('ck_shareholding_distributions_shares_7_nonnegative')),
    sa.CheckConstraint('shares_8 IS NULL OR shares_8 >= 0', name=op.f('ck_shareholding_distributions_shares_8_nonnegative')),
    sa.CheckConstraint('shares_9 IS NULL OR shares_9 >= 0', name=op.f('ck_shareholding_distributions_shares_9_nonnegative')),
    sa.CheckConstraint('total_holders IS NULL OR total_holders >= 0', name=op.f('ck_shareholding_distributions_total_holders_nonnegative')),
    sa.CheckConstraint('total_percent IS NULL OR (scale(trim_scale(total_percent)) <= 2 AND abs(total_percent) < 1e3)', name=op.f('ck_shareholding_distributions_total_percent_precision')),
    sa.CheckConstraint('total_shares IS NULL OR total_shares >= 0', name=op.f('ck_shareholding_distributions_total_shares_nonnegative')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_shareholding_distributions_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_shareholding_distributions_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'snapshot_date', 'recorded_at', name='pk_shareholding_distributions')
    )
    op.create_table('financial_report_facts',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('statement', sa.String(length=16), nullable=False),
    sa.Column('account_code', sa.String(length=16), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.CheckConstraint("concept ~ '^\\{[^{}]+\\}[^{}]+$'", name=op.f('ck_financial_report_facts_concept_qname')),
    sa.CheckConstraint("statement IN ('balance_sheet', 'income_statement', 'cash_flow')", name=op.f('ck_financial_report_facts_statement_value')),
    sa.CheckConstraint('period_start IS NULL OR period_start <= period_end', name=op.f('ck_financial_report_facts_period_order')),
    sa.CheckConstraint('value IS NOT NULL', name=op.f('ck_financial_report_facts_value_present')),
    sa.CheckConstraint('value IS NULL OR (scale(trim_scale(value)) <= 2 AND abs(value) < 1e14)', name=op.f('ck_financial_report_facts_value_precision')),
    sa.ForeignKeyConstraint(['report_id'], ['financial_reports.id'], name=op.f('fk_financial_report_facts_report_id_financial_reports'), ondelete='RESTRICT'),
    sa.UniqueConstraint('report_id', 'statement', 'concept', 'period_start', 'period_end', name='uq_financial_report_facts_identity', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION stockdc_reject_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER no_truncate_{table} BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION stockdc_reject_mutation()"
        )


def downgrade() -> None:
    # Dropping these tables would discard stored history, so refuse before any
    # change if they hold a single row (CLAUDE.md §81).
    op.execute(
        "DO $$ DECLARE n bigint := 0; t text; BEGIN "
        "FOREACH t IN ARRAY ARRAY[" + ", ".join(f"'{t}'" for t in TABLES) + "] LOOP "
        "EXECUTE format('SELECT count(*) FROM (SELECT 1 FROM %I LIMIT 1) x', t) INTO n; "
        "IF n > 0 THEN RAISE EXCEPTION 'cannot downgrade: schema v2 table % holds rows', t; END IF; "
        "END LOOP; END $$"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_report_facts')
    op.drop_table('shareholding_distributions')
    op.drop_table('monthly_revenues')
    op.drop_table('financial_reports')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
