"""create phase 1 schema

Revision ID: 94060901029e
Revises: None
Create Date: 2026-09-11 13:57:58.819931
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '94060901029e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_catalog',
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('dataset_code', name=op.f('pk_dataset_catalog'))
    )
    op.create_table('raw_artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_artifact_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('stored_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.CheckConstraint("raw_artifact_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_raw_artifacts_hash_lower_hex')),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_raw_artifacts_byte_size_nonnegative')),
    sa.CheckConstraint('position(raw_artifact_hash in storage_uri) > 0', name=op.f('ck_raw_artifacts_content_addressed_uri')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_artifacts')),
    sa.UniqueConstraint('raw_artifact_hash', name=op.f('uq_raw_artifacts_raw_artifact_hash')),
    sa.UniqueConstraint('storage_uri', name=op.f('uq_raw_artifacts_storage_uri'))
    )
    op.create_table('security',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_code', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security')),
    sa.UniqueConstraint('security_code', name=op.f('uq_security_security_code'))
    )
    op.create_table('dataset_sources',
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('supports_market_pit', sa.Boolean(), nullable=False),
    sa.Column('supports_system_pit', sa.Boolean(), nullable=False),
    sa.Column('publication_time_quality', sa.SmallInteger(), nullable=False),
    sa.Column('evidence_status', sa.String(length=32), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.CheckConstraint("evidence_status IN ('unverified', 'verified', 'disabled')", name=op.f('ck_dataset_sources_evidence_status_value')),
    sa.CheckConstraint('publication_time_quality BETWEEN 0 AND 100', name=op.f('ck_dataset_sources_publication_time_quality_range')),
    sa.ForeignKeyConstraint(['dataset_code'], ['dataset_catalog.dataset_code'], name=op.f('fk_dataset_sources_dataset_code_dataset_catalog'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dataset_code', 'source', name=op.f('pk_dataset_sources'))
    )
    op.create_index('uq_dataset_sources_one_canonical', 'dataset_sources', ['dataset_code'], unique=True, postgresql_where=sa.text('is_canonical IS true'))
    op.create_table('ingest_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f('ck_ingest_runs_status_value')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_ingest_runs_completed_after_started')),
    sa.ForeignKeyConstraint(['dataset_code', 'source'], ['dataset_sources.dataset_code', 'dataset_sources.source'], name=op.f('fk_ingest_runs_dataset_code_dataset_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_runs'))
    )
    op.create_table('raw_artifact_observations',
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_runs.id'], name=op.f('fk_raw_artifact_observations_ingest_run_id_ingest_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifacts.id'], name=op.f('fk_raw_artifact_observations_raw_artifact_id_raw_artifacts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('raw_artifact_id', 'ingest_run_id', name=op.f('pk_raw_artifact_observations'))
    )
    op.create_table('daily_price_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.Numeric(precision=30, scale=0), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('high_price IS NULL OR low_price IS NULL OR high_price >= low_price', name=op.f('ck_daily_price_versions_high_not_below_low')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_daily_price_versions_volume_nonnegative')),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_daily_price_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_daily_price_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_price_versions')),
    sa.UniqueConstraint('security_id', 'source', 'trade_date', 'business_content_hash', name='uq_daily_price_business_revision')
    )
    op.create_table('financial_filing_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('filing_key', sa.String(length=128), nullable=False),
    sa.Column('report_year', sa.SmallInteger(), nullable=False),
    sa.Column('report_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_financial_filing_versions_currency_format')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_financial_filing_versions_period_range')),
    sa.CheckConstraint('report_quarter BETWEEN 1 AND 4', name=op.f('ck_financial_filing_versions_quarter_range')),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_financial_filing_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_financial_filing_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_filing_versions')),
    sa.UniqueConstraint('source', 'filing_key', name='uq_financial_filing_source_key')
    )
    op.create_index('uq_financial_filing_business_revision', 'financial_filing_versions', ['security_id', 'source', 'report_year', 'report_quarter', 'business_content_hash'], unique=True, postgresql_where=sa.text('business_content_hash IS NOT NULL'))
    op.create_table('monthly_revenue_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('revenue_year', sa.SmallInteger(), nullable=False),
    sa.Column('revenue_month', sa.SmallInteger(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_monthly_revenue_versions_currency_format')),
    sa.CheckConstraint('revenue_month BETWEEN 1 AND 12', name=op.f('ck_monthly_revenue_versions_month_range')),
    sa.CheckConstraint('revenue_year BETWEEN 1900 AND 9999', name=op.f('ck_monthly_revenue_versions_year_range')),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_monthly_revenue_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_monthly_revenue_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_revenue_versions')),
    sa.UniqueConstraint('security_id', 'source', 'revenue_year', 'revenue_month', 'business_content_hash', name='uq_monthly_revenue_business_revision')
    )
    op.create_table('security_metadata_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('delisted_on', sa.Date(), nullable=True),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('delisted_on IS NULL OR listed_on IS NULL OR delisted_on >= listed_on', name=op.f('ck_security_metadata_versions_listing_range')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_security_metadata_versions_effective_range')),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_security_metadata_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_security_metadata_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_metadata_versions')),
    sa.UniqueConstraint('security_id', 'source', 'effective_from', 'business_content_hash', name='uq_security_metadata_business_revision')
    )
    op.create_table('tdcc_snapshot_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('security_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_tdcc_snapshot_versions_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], name=op.f('fk_tdcc_snapshot_versions_security_id_security'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdcc_snapshot_versions'))
    )
    op.create_index('uq_tdcc_snapshot_business_revision', 'tdcc_snapshot_versions', ['security_id', 'source', 'snapshot_date', 'business_content_hash'], unique=True, postgresql_where=sa.text('business_content_hash IS NOT NULL'))
    op.create_table('financial_facts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('filing_version_id', sa.BigInteger(), nullable=False),
    sa.Column('concept_qname', sa.Text(), nullable=False),
    sa.Column('context_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('entity_identifier', sa.Text(), nullable=False),
    sa.Column('period_type', sa.String(length=16), nullable=False),
    sa.Column('instant_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('explicit_dimensions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('typed_dimensions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('scenario', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('segment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('unit_identity', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('numeric_value', sa.Numeric(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('decimals', sa.String(length=32), nullable=True),
    sa.CheckConstraint("(period_type = 'instant' AND instant_date IS NOT NULL AND period_start IS NULL AND period_end IS NULL) OR (period_type = 'duration' AND instant_date IS NULL AND period_start IS NOT NULL AND period_end IS NOT NULL AND period_end >= period_start) OR (period_type = 'forever' AND instant_date IS NULL AND period_start IS NULL AND period_end IS NULL)", name=op.f('ck_financial_facts_period_shape')),
    sa.CheckConstraint("period_type IN ('instant', 'duration', 'forever')", name=op.f('ck_financial_facts_period_type_value')),
    sa.CheckConstraint('numeric_value IS NOT NULL OR text_value IS NOT NULL', name=op.f('ck_financial_facts_value_present')),
    sa.ForeignKeyConstraint(['filing_version_id'], ['financial_filing_versions.id'], name=op.f('fk_financial_facts_filing_version_id_financial_filing_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_facts')),
    sa.UniqueConstraint('filing_version_id', 'concept_qname', 'context_hash', 'unit_identity', name='uq_financial_fact_identity')
    )
    op.create_table('financial_filing_seals',
    sa.Column('filing_version_id', sa.BigInteger(), nullable=False),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['filing_version_id'], ['financial_filing_versions.id'], name=op.f('fk_financial_filing_seals_filing_version_id_financial_filing_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('filing_version_id', name=op.f('pk_financial_filing_seals'))
    )
    op.create_table('publication_evidence',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('evidence_kind', sa.String(length=24), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('evidence_source', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('quality_rank', sa.SmallInteger(), nullable=False),
    sa.Column('supersedes_evidence_id', sa.BigInteger(), nullable=True),
    sa.Column('security_metadata_version_id', sa.BigInteger(), nullable=True),
    sa.Column('daily_price_version_id', sa.BigInteger(), nullable=True),
    sa.Column('monthly_revenue_version_id', sa.BigInteger(), nullable=True),
    sa.Column('financial_filing_version_id', sa.BigInteger(), nullable=True),
    sa.Column('tdcc_snapshot_version_id', sa.BigInteger(), nullable=True),
    sa.Column('publication_evidence_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('raw_artifact_id', sa.UUID(), nullable=False),
    sa.Column('ingest_run_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("(evidence_kind IN ('assertion', 'correction') AND published_at IS NOT NULL) OR (evidence_kind IN ('retraction', 'unknown') AND published_at IS NULL)", name=op.f('ck_publication_evidence_publication_shape')),
    sa.CheckConstraint("evidence_kind IN ('assertion', 'correction', 'retraction', 'unknown')", name=op.f('ck_publication_evidence_kind_value')),
    sa.CheckConstraint('num_nonnulls(security_metadata_version_id, daily_price_version_id, monthly_revenue_version_id, financial_filing_version_id, tdcc_snapshot_version_id) = 1', name=op.f('ck_publication_evidence_exactly_one_target')),
    sa.CheckConstraint('quality_rank BETWEEN 0 AND 100', name=op.f('ck_publication_evidence_quality_rank_range')),
    sa.ForeignKeyConstraint(['daily_price_version_id'], ['daily_price_versions.id'], name=op.f('fk_publication_evidence_daily_price_version_id_daily_price_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_code', 'source'], ['dataset_sources.dataset_code', 'dataset_sources.source'], name=op.f('fk_publication_evidence_dataset_code_dataset_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_filing_version_id'], ['financial_filing_versions.id'], name=op.f('fk_publication_evidence_financial_filing_version_id_financial_filing_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['monthly_revenue_version_id'], ['monthly_revenue_versions.id'], name=op.f('fk_publication_evidence_monthly_revenue_version_id_monthly_revenue_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_artifact_id', 'ingest_run_id'], ['raw_artifact_observations.raw_artifact_id', 'raw_artifact_observations.ingest_run_id'], name=op.f('fk_publication_evidence_raw_artifact_id_raw_artifact_observations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['security_metadata_version_id'], ['security_metadata_versions.id'], name=op.f('fk_publication_evidence_security_metadata_version_id_security_metadata_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_evidence_id'], ['publication_evidence.id'], name=op.f('fk_publication_evidence_supersedes_evidence_id_publication_evidence'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tdcc_snapshot_version_id'], ['tdcc_snapshot_versions.id'], name=op.f('fk_publication_evidence_tdcc_snapshot_version_id_tdcc_snapshot_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_evidence')),
    sa.UniqueConstraint('publication_evidence_hash', name=op.f('uq_publication_evidence_publication_evidence_hash'))
    )
    op.create_table('quarterly_financial_summary',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('filing_version_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit_identity', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['filing_version_id'], ['financial_filing_versions.id'], name=op.f('fk_quarterly_financial_summary_filing_version_id_financial_filing_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarterly_financial_summary')),
    sa.UniqueConstraint('filing_version_id', 'metric_code', name='uq_quarterly_summary_metric')
    )
    op.create_table('tdcc_distribution',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('snapshot_version_id', sa.BigInteger(), nullable=False),
    sa.Column('bucket_code', sa.String(length=32), nullable=False),
    sa.Column('holder_count', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=30, scale=0), nullable=False),
    sa.Column('ownership_percent', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.CheckConstraint('holder_count >= 0', name=op.f('ck_tdcc_distribution_holder_count_nonnegative')),
    sa.CheckConstraint('ownership_percent BETWEEN 0 AND 100', name=op.f('ck_tdcc_distribution_ownership_percent_range')),
    sa.CheckConstraint('shares >= 0', name=op.f('ck_tdcc_distribution_shares_nonnegative')),
    sa.ForeignKeyConstraint(['snapshot_version_id'], ['tdcc_snapshot_versions.id'], name=op.f('fk_tdcc_distribution_snapshot_version_id_tdcc_snapshot_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tdcc_distribution')),
    sa.UniqueConstraint('snapshot_version_id', 'bucket_code', name='uq_tdcc_distribution_bucket')
    )
    op.create_table('tdcc_snapshot_seals',
    sa.Column('snapshot_version_id', sa.BigInteger(), nullable=False),
    sa.Column('business_content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_version_id'], ['tdcc_snapshot_versions.id'], name=op.f('fk_tdcc_snapshot_seals_snapshot_version_id_tdcc_snapshot_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('snapshot_version_id', name=op.f('pk_tdcc_snapshot_seals'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tdcc_snapshot_seals')
    op.drop_table('tdcc_distribution')
    op.drop_table('quarterly_financial_summary')
    op.drop_table('publication_evidence')
    op.drop_table('financial_filing_seals')
    op.drop_table('financial_facts')
    op.drop_index('uq_tdcc_snapshot_business_revision', table_name='tdcc_snapshot_versions', postgresql_where=sa.text('business_content_hash IS NOT NULL'))
    op.drop_table('tdcc_snapshot_versions')
    op.drop_table('security_metadata_versions')
    op.drop_table('monthly_revenue_versions')
    op.drop_index('uq_financial_filing_business_revision', table_name='financial_filing_versions', postgresql_where=sa.text('business_content_hash IS NOT NULL'))
    op.drop_table('financial_filing_versions')
    op.drop_table('daily_price_versions')
    op.drop_table('raw_artifact_observations')
    op.drop_table('ingest_runs')
    op.drop_index('uq_dataset_sources_one_canonical', table_name='dataset_sources', postgresql_where=sa.text('is_canonical IS true'))
    op.drop_table('dataset_sources')
    op.drop_table('security')
    op.drop_table('raw_artifacts')
    op.drop_table('dataset_catalog')
    # ### end Alembic commands ###
