"""baseline schema v2

Revision ID: a273160c0288
Revises:
Create Date: 2026-09-24

Step 35-d-3: the migration chain restarts here. The 45 migrations before it
built v1, reshaped it and finally put schema v2 (ADR-0027) beside it; every v1
table is gone, so a new database needs only this. A database built by the old
chain is moved onto this revision by `scripts/rebase_to_baseline.py`.

Value tables and the fetch log are append-only: one trigger function refuses
UPDATE, DELETE and TRUNCATE on each of them. `stocks` (today's list) and
`trading_days` are not history and are not guarded.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a273160c0288'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY = (
    "fetches",
    "daily_prices",
    "index_prices",
    "valuations",
    "institutional_flows",
    "institutional_market_flows",
    "foreign_holdings",
    "margin_trading",
    "securities_lending",
    "monthly_revenues",
    "financial_reports",
    "financial_report_facts",
    "shareholding_distributions",
    "corporate_actions",
)
ALL_TABLES = (*APPEND_ONLY, "stocks", "trading_days")

# The body is the old chain's to the byte: a database it built is rebased onto
# this revision only if the function it has is the one this creates.
REJECT_MUTATION = """CREATE FUNCTION stockdc_reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $function$
BEGIN
    RAISE EXCEPTION '% is append-only; % is forbidden', TG_TABLE_NAME, TG_OP
        USING ERRCODE = '55000';
END;
$function$"""


def upgrade() -> None:
    op.execute(REJECT_MUTATION)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('resource_key', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('adapter_version', sa.String(length=64), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('sha256', sa.LargeBinary(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("purpose IN ('first_capture', 'gap_fill', 'correction_check', 'unspecified')", name=op.f('ck_fetches_purpose_value')),
    sa.CheckConstraint("status <> 'succeeded' OR sha256 IS NOT NULL", name=op.f('ck_fetches_success_has_raw_file')),
    sa.CheckConstraint("status IN ('succeeded', 'empty', 'failed', 'quarantined')", name=op.f('ck_fetches_status_value')),
    sa.CheckConstraint('(sha256 IS NULL) = (byte_size IS NULL)', name=op.f('ck_fetches_raw_file_described')),
    sa.CheckConstraint('attempt > 0', name=op.f('ck_fetches_attempt_positive')),
    sa.CheckConstraint('sha256 IS NULL OR length(sha256) = 32', name=op.f('ck_fetches_sha256_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetches'))
    )
    op.create_index('ix_fetches_resource', 'fetches', ['dataset', 'source', 'resource_key', 'fetched_at'], unique=False)
    op.create_table('index_prices',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('index_name', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('open_value', sa.Numeric(), nullable=True),
    sa.Column('high_value', sa.Numeric(), nullable=True),
    sa.Column('low_value', sa.Numeric(), nullable=True),
    sa.Column('close_value', sa.Numeric(), nullable=True),
    sa.Column('change_points', sa.Numeric(), nullable=True),
    sa.Column('change_percent', sa.Numeric(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('change_percent IS NULL OR (scale(trim_scale(change_percent)) <= 2 AND abs(change_percent) < 1e6)', name=op.f('ck_index_prices_change_percent_precision')),
    sa.CheckConstraint('change_points IS NULL OR (scale(trim_scale(change_points)) <= 2 AND abs(change_points) < 1e10)', name=op.f('ck_index_prices_change_points_precision')),
    sa.CheckConstraint('close_value IS NULL OR (scale(trim_scale(close_value)) <= 2 AND abs(close_value) < 1e10)', name=op.f('ck_index_prices_close_value_precision')),
    sa.CheckConstraint('high_value IS NULL OR (scale(trim_scale(high_value)) <= 2 AND abs(high_value) < 1e10)', name=op.f('ck_index_prices_high_value_precision')),
    sa.CheckConstraint('low_value IS NULL OR (scale(trim_scale(low_value)) <= 2 AND abs(low_value) < 1e10)', name=op.f('ck_index_prices_low_value_precision')),
    sa.CheckConstraint('open_value IS NULL OR (scale(trim_scale(open_value)) <= 2 AND abs(open_value) < 1e10)', name=op.f('ck_index_prices_open_value_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_index_prices_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source', 'index_name', 'trade_date', 'recorded_at', name='pk_index_prices')
    )
    op.create_table('institutional_market_flows',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('institution', sa.Text(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('buy', sa.BigInteger(), nullable=True),
    sa.Column('sell', sa.BigInteger(), nullable=True),
    sa.Column('net', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_institutional_market_flows_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('source', 'trade_date', 'institution', 'recorded_at', name='pk_institutional_market_flows')
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('market', sa.String(length=3), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("btrim(stock_id) <> ''", name=op.f('ck_stocks_stock_id_nonempty')),
    sa.CheckConstraint("market IN ('sii', 'otc')", name=op.f('ck_stocks_market_value')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_stocks_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', name=op.f('pk_stocks'))
    )
    op.create_table('trading_days',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_trading_days_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trade_date', name=op.f('pk_trading_days'))
    )
    op.create_table('corporate_actions',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('close_before', sa.Numeric(), nullable=True),
    sa.Column('reference_price', sa.Numeric(), nullable=True),
    sa.Column('rights_dividend_value', sa.Numeric(), nullable=True),
    sa.Column('cash_dividend_per_share', sa.Numeric(), nullable=True),
    sa.Column('free_share_ratio', sa.Numeric(), nullable=True),
    sa.Column('rights_ratio', sa.Numeric(), nullable=True),
    sa.Column('subscription_price', sa.Numeric(), nullable=True),
    sa.Column('old_shares', sa.Numeric(), nullable=True),
    sa.Column('new_shares', sa.Numeric(), nullable=True),
    sa.Column('cash_return_per_share', sa.Numeric(), nullable=True),
    sa.Column('retracted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.Column('detail_fetch_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("(detail_fetch_id IS NOT NULL) = (source IN ('twse_twt49u', 'twse_twtauu'))", name=op.f('ck_corporate_actions_detail_fetch_for_detail_feeds')),
    sa.CheckConstraint("event_type <> ''", name=op.f('ck_corporate_actions_event_type_nonempty')),
    sa.CheckConstraint('(old_shares IS NULL) = (new_shares IS NULL)', name=op.f('ck_corporate_actions_share_pair')),
    sa.CheckConstraint('cash_dividend_per_share IS NULL OR (scale(trim_scale(cash_dividend_per_share)) <= 8 AND abs(cash_dividend_per_share) < 1e4)', name=op.f('ck_corporate_actions_cash_dividend_per_share_precision')),
    sa.CheckConstraint('cash_dividend_per_share IS NULL OR cash_dividend_per_share >= 0', name=op.f('ck_corporate_actions_cash_dividend_per_share_nonnegative')),
    sa.CheckConstraint('cash_return_per_share IS NULL OR (scale(trim_scale(cash_return_per_share)) <= 8 AND abs(cash_return_per_share) < 1e4)', name=op.f('ck_corporate_actions_cash_return_per_share_precision')),
    sa.CheckConstraint('cash_return_per_share IS NULL OR cash_return_per_share >= 0', name=op.f('ck_corporate_actions_cash_return_per_share_nonnegative')),
    sa.CheckConstraint('close_before IS NULL OR (scale(trim_scale(close_before)) <= 2 AND abs(close_before) < 1e8)', name=op.f('ck_corporate_actions_close_before_precision')),
    sa.CheckConstraint('close_before IS NULL OR close_before >= 0', name=op.f('ck_corporate_actions_close_before_nonnegative')),
    sa.CheckConstraint('free_share_ratio IS NULL OR (scale(trim_scale(free_share_ratio)) <= 12 AND abs(free_share_ratio) < 1e2)', name=op.f('ck_corporate_actions_free_share_ratio_precision')),
    sa.CheckConstraint('free_share_ratio IS NULL OR free_share_ratio >= 0', name=op.f('ck_corporate_actions_free_share_ratio_nonnegative')),
    sa.CheckConstraint('new_shares IS NULL OR (scale(trim_scale(new_shares)) <= 8 AND abs(new_shares) < 1e5)', name=op.f('ck_corporate_actions_new_shares_precision')),
    sa.CheckConstraint('new_shares IS NULL OR new_shares >= 0', name=op.f('ck_corporate_actions_new_shares_nonnegative')),
    sa.CheckConstraint('old_shares IS NULL OR (scale(trim_scale(old_shares)) <= 8 AND abs(old_shares) < 1e5)', name=op.f('ck_corporate_actions_old_shares_precision')),
    sa.CheckConstraint('old_shares IS NULL OR old_shares >= 0', name=op.f('ck_corporate_actions_old_shares_nonnegative')),
    sa.CheckConstraint('reference_price IS NULL OR (scale(trim_scale(reference_price)) <= 2 AND abs(reference_price) < 1e8)', name=op.f('ck_corporate_actions_reference_price_precision')),
    sa.CheckConstraint('reference_price IS NULL OR reference_price >= 0', name=op.f('ck_corporate_actions_reference_price_nonnegative')),
    sa.CheckConstraint('rights_dividend_value IS NULL OR (scale(trim_scale(rights_dividend_value)) <= 6 AND abs(rights_dividend_value) < 1e8)', name=op.f('ck_corporate_actions_rights_dividend_value_precision')),
    sa.CheckConstraint('rights_ratio IS NULL OR (scale(trim_scale(rights_ratio)) <= 12 AND abs(rights_ratio) < 1e2)', name=op.f('ck_corporate_actions_rights_ratio_precision')),
    sa.CheckConstraint('rights_ratio IS NULL OR rights_ratio >= 0', name=op.f('ck_corporate_actions_rights_ratio_nonnegative')),
    sa.CheckConstraint('subscription_price IS NULL OR (scale(trim_scale(subscription_price)) <= 2 AND abs(subscription_price) < 1e8)', name=op.f('ck_corporate_actions_subscription_price_precision')),
    sa.CheckConstraint('subscription_price IS NULL OR subscription_price >= 0', name=op.f('ck_corporate_actions_subscription_price_nonnegative')),
    sa.ForeignKeyConstraint(['detail_fetch_id'], ['fetches.id'], name=op.f('fk_corporate_actions_detail_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_corporate_actions_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_corporate_actions_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'ex_date', 'recorded_at', name='pk_corporate_actions')
    )
    op.create_table('daily_prices',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=True),
    sa.Column('high_price', sa.Numeric(), nullable=True),
    sa.Column('low_price', sa.Numeric(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_value', sa.BigInteger(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('price_change', sa.Numeric(), nullable=True),
    sa.Column('price_direction', sa.String(length=4), nullable=True),
    sa.Column('last_bid_price', sa.Numeric(), nullable=True),
    sa.Column('last_ask_price', sa.Numeric(), nullable=True),
    sa.Column('last_bid_volume', sa.BigInteger(), nullable=True),
    sa.Column('last_ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('close_price IS NULL OR (scale(trim_scale(close_price)) <= 2 AND abs(close_price) < 1e8)', name=op.f('ck_daily_prices_close_price_precision')),
    sa.CheckConstraint('high_price IS NULL OR (scale(trim_scale(high_price)) <= 2 AND abs(high_price) < 1e8)', name=op.f('ck_daily_prices_high_price_precision')),
    sa.CheckConstraint('last_ask_price IS NULL OR (scale(trim_scale(last_ask_price)) <= 2 AND abs(last_ask_price) < 1e8)', name=op.f('ck_daily_prices_last_ask_price_precision')),
    sa.CheckConstraint('last_ask_volume IS NULL OR last_ask_volume >= 0', name=op.f('ck_daily_prices_last_ask_volume_nonnegative')),
    sa.CheckConstraint('last_bid_price IS NULL OR (scale(trim_scale(last_bid_price)) <= 2 AND abs(last_bid_price) < 1e8)', name=op.f('ck_daily_prices_last_bid_price_precision')),
    sa.CheckConstraint('last_bid_volume IS NULL OR last_bid_volume >= 0', name=op.f('ck_daily_prices_last_bid_volume_nonnegative')),
    sa.CheckConstraint('low_price IS NULL OR (scale(trim_scale(low_price)) <= 2 AND abs(low_price) < 1e8)', name=op.f('ck_daily_prices_low_price_precision')),
    sa.CheckConstraint('open_price IS NULL OR (scale(trim_scale(open_price)) <= 2 AND abs(open_price) < 1e8)', name=op.f('ck_daily_prices_open_price_precision')),
    sa.CheckConstraint('price_change IS NULL OR (scale(trim_scale(price_change)) <= 2 AND abs(price_change) < 1e8)', name=op.f('ck_daily_prices_price_change_precision')),
    sa.CheckConstraint('trade_count IS NULL OR trade_count >= 0', name=op.f('ck_daily_prices_trade_count_nonnegative')),
    sa.CheckConstraint('trade_value IS NULL OR trade_value >= 0', name=op.f('ck_daily_prices_trade_value_nonnegative')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_daily_prices_volume_nonnegative')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_daily_prices_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_daily_prices_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_daily_prices')
    )
    op.create_table('financial_reports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('report_year', sa.SmallInteger(), nullable=False),
    sa.Column('report_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('report_category', sa.String(length=12), nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("report_category IN ('consolidated', 'individual')", name=op.f('ck_financial_reports_report_category_value')),
    sa.CheckConstraint('report_quarter BETWEEN 1 AND 4', name=op.f('ck_financial_reports_report_quarter_range')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_financial_reports_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_financial_reports_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_reports')),
    sa.UniqueConstraint('stock_id', 'report_year', 'report_quarter', 'recorded_at', name='uq_financial_reports_version')
    )
    op.create_table('foreign_holdings',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('issued_shares', sa.BigInteger(), nullable=True),
    sa.Column('investable_shares', sa.BigInteger(), nullable=True),
    sa.Column('held_shares', sa.BigInteger(), nullable=True),
    sa.Column('investable_ratio', sa.Numeric(), nullable=True),
    sa.Column('held_ratio', sa.Numeric(), nullable=True),
    sa.Column('foreign_legal_limit_ratio', sa.Numeric(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('foreign_legal_limit_ratio IS NULL OR (scale(trim_scale(foreign_legal_limit_ratio)) <= 2 AND abs(foreign_legal_limit_ratio) < 1e4)', name=op.f('ck_foreign_holdings_foreign_legal_limit_ratio_precision')),
    sa.CheckConstraint('held_ratio IS NULL OR (scale(trim_scale(held_ratio)) <= 2 AND abs(held_ratio) < 1e4)', name=op.f('ck_foreign_holdings_held_ratio_precision')),
    sa.CheckConstraint('investable_ratio IS NULL OR (scale(trim_scale(investable_ratio)) <= 2 AND abs(investable_ratio) < 1e4)', name=op.f('ck_foreign_holdings_investable_ratio_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_foreign_holdings_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_foreign_holdings_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_foreign_holdings')
    )
    op.create_table('institutional_flows',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('foreign_buy', sa.BigInteger(), nullable=True),
    sa.Column('foreign_sell', sa.BigInteger(), nullable=True),
    sa.Column('foreign_net', sa.BigInteger(), nullable=True),
    sa.Column('foreign_dealer_buy', sa.BigInteger(), nullable=True),
    sa.Column('foreign_dealer_sell', sa.BigInteger(), nullable=True),
    sa.Column('foreign_dealer_net', sa.BigInteger(), nullable=True),
    sa.Column('trust_buy', sa.BigInteger(), nullable=True),
    sa.Column('trust_sell', sa.BigInteger(), nullable=True),
    sa.Column('trust_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_buy', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_sell', sa.BigInteger(), nullable=True),
    sa.Column('dealer_self_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_buy', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_sell', sa.BigInteger(), nullable=True),
    sa.Column('dealer_hedge_net', sa.BigInteger(), nullable=True),
    sa.Column('dealer_net', sa.BigInteger(), nullable=True),
    sa.Column('total_net', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_institutional_flows_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_institutional_flows_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_institutional_flows')
    )
    op.create_table('margin_trading',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('margin_buy', sa.BigInteger(), nullable=True),
    sa.Column('margin_sell', sa.BigInteger(), nullable=True),
    sa.Column('margin_cash_repayment', sa.BigInteger(), nullable=True),
    sa.Column('margin_previous_balance', sa.BigInteger(), nullable=True),
    sa.Column('margin_balance', sa.BigInteger(), nullable=True),
    sa.Column('margin_limit', sa.BigInteger(), nullable=True),
    sa.Column('short_buy', sa.BigInteger(), nullable=True),
    sa.Column('short_sell', sa.BigInteger(), nullable=True),
    sa.Column('short_stock_repayment', sa.BigInteger(), nullable=True),
    sa.Column('short_previous_balance', sa.BigInteger(), nullable=True),
    sa.Column('short_balance', sa.BigInteger(), nullable=True),
    sa.Column('short_limit', sa.BigInteger(), nullable=True),
    sa.Column('offset_balance', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_margin_trading_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_margin_trading_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_margin_trading')
    )
    op.create_table('monthly_revenues',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('revenue_month', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=False),
    sa.Column('revenue_last_month', sa.BigInteger(), nullable=True),
    sa.Column('revenue_last_year_month', sa.BigInteger(), nullable=True),
    sa.Column('cumulative_revenue', sa.BigInteger(), nullable=True),
    sa.Column('cumulative_revenue_last_year', sa.BigInteger(), nullable=True),
    sa.Column('mom_pct', sa.Numeric(), nullable=True),
    sa.Column('yoy_pct', sa.Numeric(), nullable=True),
    sa.Column('cumulative_yoy_pct', sa.Numeric(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("revenue_month = date_trunc('month', revenue_month)::date", name=op.f('ck_monthly_revenues_revenue_month_first_day')),
    sa.CheckConstraint('cumulative_yoy_pct IS NULL OR (scale(trim_scale(cumulative_yoy_pct)) <= 2 AND abs(cumulative_yoy_pct) < 1e8)', name=op.f('ck_monthly_revenues_cumulative_yoy_pct_precision')),
    sa.CheckConstraint('mom_pct IS NULL OR (scale(trim_scale(mom_pct)) <= 2 AND abs(mom_pct) < 1e8)', name=op.f('ck_monthly_revenues_mom_pct_precision')),
    sa.CheckConstraint('yoy_pct IS NULL OR (scale(trim_scale(yoy_pct)) <= 2 AND abs(yoy_pct) < 1e8)', name=op.f('ck_monthly_revenues_yoy_pct_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_monthly_revenues_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_monthly_revenues_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'revenue_month', 'recorded_at', name='pk_monthly_revenues')
    )
    op.create_table('securities_lending',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('previous_balance', sa.BigInteger(), nullable=True),
    sa.Column('sold', sa.BigInteger(), nullable=True),
    sa.Column('returned', sa.BigInteger(), nullable=True),
    sa.Column('adjustment', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('next_limit', sa.BigInteger(), nullable=True),
    sa.Column('next_available_limit', sa.BigInteger(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_securities_lending_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_securities_lending_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_securities_lending')
    )
    op.create_table('shareholding_distributions',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('holders_1', sa.BigInteger(), nullable=True),
    sa.Column('shares_1', sa.BigInteger(), nullable=True),
    sa.Column('percent_1', sa.Numeric(), nullable=True),
    sa.Column('holders_2', sa.BigInteger(), nullable=True),
    sa.Column('shares_2', sa.BigInteger(), nullable=True),
    sa.Column('percent_2', sa.Numeric(), nullable=True),
    sa.Column('holders_3', sa.BigInteger(), nullable=True),
    sa.Column('shares_3', sa.BigInteger(), nullable=True),
    sa.Column('percent_3', sa.Numeric(), nullable=True),
    sa.Column('holders_4', sa.BigInteger(), nullable=True),
    sa.Column('shares_4', sa.BigInteger(), nullable=True),
    sa.Column('percent_4', sa.Numeric(), nullable=True),
    sa.Column('holders_5', sa.BigInteger(), nullable=True),
    sa.Column('shares_5', sa.BigInteger(), nullable=True),
    sa.Column('percent_5', sa.Numeric(), nullable=True),
    sa.Column('holders_6', sa.BigInteger(), nullable=True),
    sa.Column('shares_6', sa.BigInteger(), nullable=True),
    sa.Column('percent_6', sa.Numeric(), nullable=True),
    sa.Column('holders_7', sa.BigInteger(), nullable=True),
    sa.Column('shares_7', sa.BigInteger(), nullable=True),
    sa.Column('percent_7', sa.Numeric(), nullable=True),
    sa.Column('holders_8', sa.BigInteger(), nullable=True),
    sa.Column('shares_8', sa.BigInteger(), nullable=True),
    sa.Column('percent_8', sa.Numeric(), nullable=True),
    sa.Column('holders_9', sa.BigInteger(), nullable=True),
    sa.Column('shares_9', sa.BigInteger(), nullable=True),
    sa.Column('percent_9', sa.Numeric(), nullable=True),
    sa.Column('holders_10', sa.BigInteger(), nullable=True),
    sa.Column('shares_10', sa.BigInteger(), nullable=True),
    sa.Column('percent_10', sa.Numeric(), nullable=True),
    sa.Column('holders_11', sa.BigInteger(), nullable=True),
    sa.Column('shares_11', sa.BigInteger(), nullable=True),
    sa.Column('percent_11', sa.Numeric(), nullable=True),
    sa.Column('holders_12', sa.BigInteger(), nullable=True),
    sa.Column('shares_12', sa.BigInteger(), nullable=True),
    sa.Column('percent_12', sa.Numeric(), nullable=True),
    sa.Column('holders_13', sa.BigInteger(), nullable=True),
    sa.Column('shares_13', sa.BigInteger(), nullable=True),
    sa.Column('percent_13', sa.Numeric(), nullable=True),
    sa.Column('holders_14', sa.BigInteger(), nullable=True),
    sa.Column('shares_14', sa.BigInteger(), nullable=True),
    sa.Column('percent_14', sa.Numeric(), nullable=True),
    sa.Column('holders_15', sa.BigInteger(), nullable=True),
    sa.Column('shares_15', sa.BigInteger(), nullable=True),
    sa.Column('percent_15', sa.Numeric(), nullable=True),
    sa.Column('adjustment_shares', sa.BigInteger(), nullable=True),
    sa.Column('adjustment_percent', sa.Numeric(), nullable=True),
    sa.Column('total_holders', sa.BigInteger(), nullable=True),
    sa.Column('total_shares', sa.BigInteger(), nullable=True),
    sa.Column('total_percent', sa.Numeric(), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('adjustment_percent IS NULL OR (scale(trim_scale(adjustment_percent)) <= 2 AND abs(adjustment_percent) < 1e3)', name=op.f('ck_shareholding_distributions_adjustment_percent_precision')),
    sa.CheckConstraint('holders_1 IS NULL OR holders_1 >= 0', name=op.f('ck_shareholding_distributions_holders_1_nonnegative')),
    sa.CheckConstraint('holders_10 IS NULL OR holders_10 >= 0', name=op.f('ck_shareholding_distributions_holders_10_nonnegative')),
    sa.CheckConstraint('holders_11 IS NULL OR holders_11 >= 0', name=op.f('ck_shareholding_distributions_holders_11_nonnegative')),
    sa.CheckConstraint('holders_12 IS NULL OR holders_12 >= 0', name=op.f('ck_shareholding_distributions_holders_12_nonnegative')),
    sa.CheckConstraint('holders_13 IS NULL OR holders_13 >= 0', name=op.f('ck_shareholding_distributions_holders_13_nonnegative')),
    sa.CheckConstraint('holders_14 IS NULL OR holders_14 >= 0', name=op.f('ck_shareholding_distributions_holders_14_nonnegative')),
    sa.CheckConstraint('holders_15 IS NULL OR holders_15 >= 0', name=op.f('ck_shareholding_distributions_holders_15_nonnegative')),
    sa.CheckConstraint('holders_2 IS NULL OR holders_2 >= 0', name=op.f('ck_shareholding_distributions_holders_2_nonnegative')),
    sa.CheckConstraint('holders_3 IS NULL OR holders_3 >= 0', name=op.f('ck_shareholding_distributions_holders_3_nonnegative')),
    sa.CheckConstraint('holders_4 IS NULL OR holders_4 >= 0', name=op.f('ck_shareholding_distributions_holders_4_nonnegative')),
    sa.CheckConstraint('holders_5 IS NULL OR holders_5 >= 0', name=op.f('ck_shareholding_distributions_holders_5_nonnegative')),
    sa.CheckConstraint('holders_6 IS NULL OR holders_6 >= 0', name=op.f('ck_shareholding_distributions_holders_6_nonnegative')),
    sa.CheckConstraint('holders_7 IS NULL OR holders_7 >= 0', name=op.f('ck_shareholding_distributions_holders_7_nonnegative')),
    sa.CheckConstraint('holders_8 IS NULL OR holders_8 >= 0', name=op.f('ck_shareholding_distributions_holders_8_nonnegative')),
    sa.CheckConstraint('holders_9 IS NULL OR holders_9 >= 0', name=op.f('ck_shareholding_distributions_holders_9_nonnegative')),
    sa.CheckConstraint('percent_1 IS NULL OR (scale(trim_scale(percent_1)) <= 2 AND abs(percent_1) < 1e3)', name=op.f('ck_shareholding_distributions_percent_1_precision')),
    sa.CheckConstraint('percent_10 IS NULL OR (scale(trim_scale(percent_10)) <= 2 AND abs(percent_10) < 1e3)', name=op.f('ck_shareholding_distributions_percent_10_precision')),
    sa.CheckConstraint('percent_11 IS NULL OR (scale(trim_scale(percent_11)) <= 2 AND abs(percent_11) < 1e3)', name=op.f('ck_shareholding_distributions_percent_11_precision')),
    sa.CheckConstraint('percent_12 IS NULL OR (scale(trim_scale(percent_12)) <= 2 AND abs(percent_12) < 1e3)', name=op.f('ck_shareholding_distributions_percent_12_precision')),
    sa.CheckConstraint('percent_13 IS NULL OR (scale(trim_scale(percent_13)) <= 2 AND abs(percent_13) < 1e3)', name=op.f('ck_shareholding_distributions_percent_13_precision')),
    sa.CheckConstraint('percent_14 IS NULL OR (scale(trim_scale(percent_14)) <= 2 AND abs(percent_14) < 1e3)', name=op.f('ck_shareholding_distributions_percent_14_precision')),
    sa.CheckConstraint('percent_15 IS NULL OR (scale(trim_scale(percent_15)) <= 2 AND abs(percent_15) < 1e3)', name=op.f('ck_shareholding_distributions_percent_15_precision')),
    sa.CheckConstraint('percent_2 IS NULL OR (scale(trim_scale(percent_2)) <= 2 AND abs(percent_2) < 1e3)', name=op.f('ck_shareholding_distributions_percent_2_precision')),
    sa.CheckConstraint('percent_3 IS NULL OR (scale(trim_scale(percent_3)) <= 2 AND abs(percent_3) < 1e3)', name=op.f('ck_shareholding_distributions_percent_3_precision')),
    sa.CheckConstraint('percent_4 IS NULL OR (scale(trim_scale(percent_4)) <= 2 AND abs(percent_4) < 1e3)', name=op.f('ck_shareholding_distributions_percent_4_precision')),
    sa.CheckConstraint('percent_5 IS NULL OR (scale(trim_scale(percent_5)) <= 2 AND abs(percent_5) < 1e3)', name=op.f('ck_shareholding_distributions_percent_5_precision')),
    sa.CheckConstraint('percent_6 IS NULL OR (scale(trim_scale(percent_6)) <= 2 AND abs(percent_6) < 1e3)', name=op.f('ck_shareholding_distributions_percent_6_precision')),
    sa.CheckConstraint('percent_7 IS NULL OR (scale(trim_scale(percent_7)) <= 2 AND abs(percent_7) < 1e3)', name=op.f('ck_shareholding_distributions_percent_7_precision')),
    sa.CheckConstraint('percent_8 IS NULL OR (scale(trim_scale(percent_8)) <= 2 AND abs(percent_8) < 1e3)', name=op.f('ck_shareholding_distributions_percent_8_precision')),
    sa.CheckConstraint('percent_9 IS NULL OR (scale(trim_scale(percent_9)) <= 2 AND abs(percent_9) < 1e3)', name=op.f('ck_shareholding_distributions_percent_9_precision')),
    sa.CheckConstraint('shares_1 IS NULL OR shares_1 >= 0', name=op.f('ck_shareholding_distributions_shares_1_nonnegative')),
    sa.CheckConstraint('shares_10 IS NULL OR shares_10 >= 0', name=op.f('ck_shareholding_distributions_shares_10_nonnegative')),
    sa.CheckConstraint('shares_11 IS NULL OR shares_11 >= 0', name=op.f('ck_shareholding_distributions_shares_11_nonnegative')),
    sa.CheckConstraint('shares_12 IS NULL OR shares_12 >= 0', name=op.f('ck_shareholding_distributions_shares_12_nonnegative')),
    sa.CheckConstraint('shares_13 IS NULL OR shares_13 >= 0', name=op.f('ck_shareholding_distributions_shares_13_nonnegative')),
    sa.CheckConstraint('shares_14 IS NULL OR shares_14 >= 0', name=op.f('ck_shareholding_distributions_shares_14_nonnegative')),
    sa.CheckConstraint('shares_15 IS NULL OR shares_15 >= 0', name=op.f('ck_shareholding_distributions_shares_15_nonnegative')),
    sa.CheckConstraint('shares_2 IS NULL OR shares_2 >= 0', name=op.f('ck_shareholding_distributions_shares_2_nonnegative')),
    sa.CheckConstraint('shares_3 IS NULL OR shares_3 >= 0', name=op.f('ck_shareholding_distributions_shares_3_nonnegative')),
    sa.CheckConstraint('shares_4 IS NULL OR shares_4 >= 0', name=op.f('ck_shareholding_distributions_shares_4_nonnegative')),
    sa.CheckConstraint('shares_5 IS NULL OR shares_5 >= 0', name=op.f('ck_shareholding_distributions_shares_5_nonnegative')),
    sa.CheckConstraint('shares_6 IS NULL OR shares_6 >= 0', name=op.f('ck_shareholding_distributions_shares_6_nonnegative')),
    sa.CheckConstraint('shares_7 IS NULL OR shares_7 >= 0', name=op.f('ck_shareholding_distributions_shares_7_nonnegative')),
    sa.CheckConstraint('shares_8 IS NULL OR shares_8 >= 0', name=op.f('ck_shareholding_distributions_shares_8_nonnegative')),
    sa.CheckConstraint('shares_9 IS NULL OR shares_9 >= 0', name=op.f('ck_shareholding_distributions_shares_9_nonnegative')),
    sa.CheckConstraint('total_holders IS NULL OR total_holders >= 0', name=op.f('ck_shareholding_distributions_total_holders_nonnegative')),
    sa.CheckConstraint('total_percent IS NULL OR (scale(trim_scale(total_percent)) <= 2 AND abs(total_percent) < 1e3)', name=op.f('ck_shareholding_distributions_total_percent_precision')),
    sa.CheckConstraint('total_shares IS NULL OR total_shares >= 0', name=op.f('ck_shareholding_distributions_total_shares_nonnegative')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_shareholding_distributions_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_shareholding_distributions_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'snapshot_date', 'recorded_at', name='pk_shareholding_distributions')
    )
    op.create_table('valuations',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('statement_timestamp()'), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('dividend_year', sa.SmallInteger(), nullable=True),
    sa.Column('report_period', sa.String(length=8), nullable=True),
    sa.Column('fetch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('dividend_yield IS NULL OR (scale(trim_scale(dividend_yield)) <= 2 AND abs(dividend_yield) < 1e6)', name=op.f('ck_valuations_dividend_yield_precision')),
    sa.CheckConstraint('pb_ratio IS NULL OR (scale(trim_scale(pb_ratio)) <= 2 AND abs(pb_ratio) < 1e8)', name=op.f('ck_valuations_pb_ratio_precision')),
    sa.CheckConstraint('pe_ratio IS NULL OR (scale(trim_scale(pe_ratio)) <= 2 AND abs(pe_ratio) < 1e8)', name=op.f('ck_valuations_pe_ratio_precision')),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], name=op.f('fk_valuations_fetch_id_fetches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_valuations_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'trade_date', 'recorded_at', name='pk_valuations')
    )
    op.create_table('financial_report_facts',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('statement', sa.String(length=16), nullable=False),
    sa.Column('account_code', sa.String(length=16), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.CheckConstraint("concept ~ '^\\{[^{}]+\\}[^{}]+$'", name=op.f('ck_financial_report_facts_concept_qname')),
    sa.CheckConstraint("statement IN ('balance_sheet', 'income_statement', 'cash_flow')", name=op.f('ck_financial_report_facts_statement_value')),
    sa.CheckConstraint('period_start IS NULL OR period_start <= period_end', name=op.f('ck_financial_report_facts_period_order')),
    sa.CheckConstraint('value IS NOT NULL', name=op.f('ck_financial_report_facts_value_present')),
    sa.CheckConstraint('value IS NULL OR (scale(trim_scale(value)) <= 2 AND abs(value) < 1e14)', name=op.f('ck_financial_report_facts_value_precision')),
    sa.ForeignKeyConstraint(['report_id'], ['financial_reports.id'], name=op.f('fk_financial_report_facts_report_id_financial_reports'), ondelete='RESTRICT'),
    sa.UniqueConstraint('report_id', 'statement', 'concept', 'period_start', 'period_end', name='uq_financial_report_facts_identity', postgresql_nulls_not_distinct=True)
    )
    # ### end Alembic commands ###
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION stockdc_reject_mutation()"
        )
        op.execute(
            f"CREATE TRIGGER no_truncate_{table} BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION stockdc_reject_mutation()"
        )


def downgrade() -> None:
    # Dropping these tables would discard stored history, so refuse before any
    # change if they hold a single row (CLAUDE.md §81).
    op.execute(
        "DO $$ DECLARE n bigint := 0; t text; BEGIN "
        "FOREACH t IN ARRAY ARRAY[" + ", ".join(f"'{t}'" for t in ALL_TABLES) + "] LOOP "
        "EXECUTE format('SELECT count(*) FROM (SELECT 1 FROM %I LIMIT 1) x', t) INTO n; "
        "IF n > 0 THEN RAISE EXCEPTION 'cannot downgrade: % holds rows', t; END IF; "
        "END LOOP; END $$"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_report_facts')
    op.drop_table('valuations')
    op.drop_table('shareholding_distributions')
    op.drop_table('securities_lending')
    op.drop_table('monthly_revenues')
    op.drop_table('margin_trading')
    op.drop_table('institutional_flows')
    op.drop_table('foreign_holdings')
    op.drop_table('financial_reports')
    op.drop_table('daily_prices')
    op.drop_table('corporate_actions')
    op.drop_table('trading_days')
    op.drop_table('stocks')
    op.drop_table('institutional_market_flows')
    op.drop_table('index_prices')
    op.drop_index('ix_fetches_resource', table_name='fetches')
    op.drop_table('fetches')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION stockdc_reject_mutation()")
