"""step 26-d shareholding concentration table

Revision ID: c3f1f515e3df
Revises: 0f6386ea08db
Create Date: 2026-09-25

`shareholding_concentration` (Step 26-d): legacy's TDCC large/mid/small holder
groups and their week-over-week changes, one wide row per (stock, source,
snapshot date). Derived, so no append-only trigger, and the downgrade drops it
without a guard: every row is recomputed from stored inputs (CLAUDE.md §81).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c3f1f515e3df'
down_revision: str | None = '0f6386ea08db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shareholding_concentration',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('large_holder_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('mid_holder_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('small_holder_ratio', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('concentration_spread', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('large_holder_count', sa.BigInteger(), nullable=True),
    sa.Column('small_holder_count', sa.BigInteger(), nullable=True),
    sa.Column('large_holder_ratio_wow', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('mid_holder_ratio_wow', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('small_holder_ratio_wow', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('concentration_spread_wow', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], name=op.f('fk_shareholding_concentration_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id', 'source', 'snapshot_date', name='pk_shareholding_concentration')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shareholding_concentration')
    # ### end Alembic commands ###
