#!/usr/bin/env python
"""Step 35-c-2 acceptance: live fetches through the v2 write path add no row.

For a few periods, copy what `stockdc_backfill` holds in v2 (the history
Step 35-c-1 migrated) into a scratch database, then fetch the same periods live
with purpose `correction_check`. The write path appends only what differs from
the latest stored row or report version, so a write path that maps every value
the way the migration did appends nothing; anything appended is printed, key
and values, for classification. One kind is expected and reported apart: a
stock on today's list that v1 never registered (newly listed) has no migrated
row, yet MOPS pages, regenerated by current issuer status, list its past months.

- monthly revenue: every page (domestic and foreign, both markets) of `--month`;
- financial reports: `--report CODE:YYYYQn`, 合併 then 個體;
- TDCC: the week OpenData serves now, compared with the same week if migrated.

The backfill database is only read; the scratch one is dropped unless `--keep`.

    .venv/bin/python scripts/verify_v2_35c_write_path.py \\
        --month 2020-01 --month 2026-07 --report 1101:2025Q1 --report 2330:2023Q2
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import date

import sqlalchemy as sa

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from alembic import command
from alembic.config import Config

from stock_data_center.db import schema_v2 as v2
from stock_data_center.ingestion.http import (
    HostRateGovernor,
    HttpSourceFetcher,
    RetryingFetcher,
)
from stock_data_center.ingestion.models import TDCCShareholdingRequest
from stock_data_center.v2 import financial_reports as fr
from stock_data_center.v2 import monthly_revenue, shareholding
from stock_data_center.v2.backfill import HOST_INTERVALS, _unit, run
from stock_data_center.v2.exchange_daily import ingest
from stock_data_center.v2.fetch_log import current_git_commit

SERVER = "postgresql+psycopg://stockdc:stockdc@localhost:26519"
BACKFILL = f"{SERVER}/stockdc_backfill"
SCRATCH = "stockdc_v2_verify_35c"
TDCC_HOST = "opendata.tdcc.com.tw"


def _admin(sql: str) -> None:
    admin = sa.create_engine(f"{SERVER}/postgres", isolation_level="AUTOCOMMIT")
    with admin.connect() as connection:
        connection.exec_driver_sql(sql)
    admin.dispose()


def _recreate() -> str:
    _admin(f"DROP DATABASE IF EXISTS {SCRATCH}")
    _admin(f"CREATE DATABASE {SCRATCH} OWNER stockdc")
    url = f"{SERVER}/{SCRATCH}"
    config = Config("alembic.ini")
    config.set_main_option("sqlalchemy.url", url)
    config.attributes["database_url"] = url
    command.upgrade(config, "head")
    return url


def _copy(source, target, months: list[date], reports: list[tuple[str, int, int]],
          tdcc_week: date | None) -> dict[str, int]:
    r = v2.financial_reports
    selections = {
        v2.stocks: sa.select(v2.stocks),
        v2.monthly_revenues: sa.select(v2.monthly_revenues).where(
            v2.monthly_revenues.c.revenue_month.in_(months)),
        r: sa.select(r).where(sa.tuple_(r.c.stock_id, r.c.report_year, r.c.report_quarter)
                              .in_(reports)) if reports else None,
        v2.shareholding_distributions: sa.select(v2.shareholding_distributions).where(
            v2.shareholding_distributions.c.snapshot_date == tdcc_week),
    }
    copied: dict[str, int] = {}
    with source.connect() as reader, target.begin() as writer:
        rows = {table: [dict(x) for x in reader.execute(q).mappings()] if q is not None else []
                for table, q in selections.items()}
        report_ids = [row["id"] for row in rows[r]]
        rows[v2.financial_report_facts] = [dict(x) for x in reader.execute(
            sa.select(v2.financial_report_facts)
            .where(v2.financial_report_facts.c.report_id.in_(report_ids))).mappings()]
        fetch_ids = {row["fetch_id"] for batch in rows.values() for row in batch if "fetch_id" in row}
        fetches = [dict(x) for x in reader.execute(
            sa.select(v2.fetches).where(v2.fetches.c.id.in_(fetch_ids))).mappings()]
        writer.execute(sa.insert(v2.fetches), fetches)
        copied["fetches"] = len(fetches)
        for table in (v2.stocks, v2.monthly_revenues, r, v2.financial_report_facts,
                      v2.shareholding_distributions):
            if rows[table]:
                writer.execute(sa.insert(table), rows[table])
            copied[table.name] = len(rows[table])
    return copied


def _appended(target, since) -> dict[str, list]:
    """Every row or report version this run wrote, beside the one it differs from."""
    found: dict[str, list] = {}
    with target.connect() as c:
        mr = v2.monthly_revenues
        found["monthly_revenues"] = [
            {k: str(v) for k, v in row.items()} for row in c.execute(
                sa.select(mr).where(mr.c.recorded_at >= since)).mappings()]
        sd = v2.shareholding_distributions
        found["shareholding_distributions"] = [
            {k: str(row[k]) for k in ("stock_id", "snapshot_date", "total_shares")}
            for row in c.execute(sa.select(sd).where(sd.c.recorded_at >= since)).mappings()]
        r, f = v2.financial_reports, v2.financial_report_facts
        versions = []
        for new in c.execute(sa.select(r).where(r.c.recorded_at >= since)).mappings():
            old = c.execute(sa.select(r.c.id, r.c.report_category).where(
                r.c.stock_id == new["stock_id"], r.c.report_year == new["report_year"],
                r.c.report_quarter == new["report_quarter"], r.c.recorded_at < since)
                .order_by(r.c.recorded_at.desc()).limit(1)).first()
            cols = (f.c.statement, f.c.account_code, f.c.concept, f.c.period_start,
                    f.c.period_end, f.c.unit, f.c.value)
            now = set(c.execute(sa.select(*cols).where(f.c.report_id == new["id"])).all())
            was = set(c.execute(sa.select(*cols).where(f.c.report_id == old.id)).all()) if old else set()
            versions.append({
                "key": f"{new['stock_id']} {new['report_year']}Q{new['report_quarter']}",
                "was_category": old.report_category if old else None,
                "category": new["report_category"],
                "facts": len(now),
                "only_new": [str(x) for x in sorted(now - was, key=str)][:20],
                "only_old": [str(x) for x in sorted(was - now, key=str)][:20],
            })
        found["financial_reports"] = versions
    return found


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--month", action="append", default=[],
                        type=lambda s: date.fromisoformat(f"{s}-01"))
    parser.add_argument("--report", action="append", default=[],
                        type=lambda s: (s.split(":")[0], int(s[-6:-2]), int(s[-1])))
    parser.add_argument("--keep", action="store_true")
    args = parser.parse_args()

    source = sa.create_engine(BACKFILL)
    target = sa.create_engine(_recreate())
    try:
        fetcher = RetryingFetcher(HttpSourceFetcher(
            governor=HostRateGovernor({**HOST_INTERVALS, TDCC_HOST: 1.5})))
        git_commit = current_git_commit()
        # The week OpenData serves now decides which migrated week to compare.
        tdcc_job = shareholding.JOBS["shareholding_distributions/tdcc_opendata"]
        served = fetcher.fetch(tdcc_job.adapter.resource(TDCCShareholdingRequest()))
        week = tdcc_job.adapter.parse(served.content, TDCCShareholdingRequest()).snapshot_date
        copied = _copy(source, target, sorted(args.month), args.report, week)
        print(json.dumps({"copied": copied, "tdcc_week": str(week)}), file=sys.stderr)
        with target.connect() as connection:
            since = connection.scalar(sa.select(sa.func.statement_timestamp()))
        began = time.monotonic()

        def progress(key, period, outcome):
            print(f"{key} {period} {outcome.status} +{outcome.appended} ={outcome.unchanged} "
                  f"{outcome.reason_code or ''}", file=sys.stderr, flush=True)

        common = {"fetcher": fetcher, "git_commit": git_commit, "purpose": "correction_check",
                  "refetch": True, "progress": progress}
        report: dict[str, dict] = {}
        for month in sorted(args.month):
            for job in monthly_revenue.JOBS.values():
                with _unit(target) as connection:
                    outcome = ingest(connection, job, month, fetcher=fetcher,
                                     git_commit=git_commit, purpose="correction_check")
                progress(job.key, month, outcome)
                report[f"{job.key} {month:%Y-%m}"] = {
                    "status": outcome.status, "appended": outcome.appended,
                    "unchanged": outcome.unchanged, "out_of_scope": outcome.out_of_scope}
        report["shareholding_distributions/tdcc_opendata"] = run(
            target, [tdcc_job], week, week, **common)["shareholding_distributions/tdcc_opendata"]
        for stock_id, year, quarter in args.report:
            with _unit(target) as connection:
                outcome = fr.ingest(connection, stock_id, year, quarter, fetcher=fetcher,
                                    git_commit=git_commit, purpose="correction_check")
            progress(fr.KEY, f"{stock_id} {year}Q{quarter}", outcome)
            report[f"{fr.KEY} {stock_id} {year}Q{quarter}"] = {
                "status": outcome.status, "appended": outcome.appended,
                "unchanged": outcome.unchanged, "facts": outcome.parsed,
                "reason": outcome.reason_code}
        appended = _appended(target, since)
        # A stock the migrated history never held (listed after v1 last ran) has
        # no row to agree with: reported apart, like 35-b-1's later TAIEX dates.
        new_stocks: dict[str, list] = {}
        with source.connect() as reader:
            for table in ("monthly_revenues", "shareholding_distributions"):
                held = set(reader.scalars(sa.text(
                    f"SELECT DISTINCT stock_id FROM {table} WHERE stock_id = ANY(:s)"),
                    {"s": [row["stock_id"] for row in appended[table]]}))
                new_stocks[table] = [row for row in appended[table] if row["stock_id"] not in held]
                appended[table] = [row for row in appended[table] if row["stock_id"] in held]
        print(json.dumps({"seconds": round(time.monotonic() - began, 1), "report": report,
                          "differing": appended, "stock_not_in_migrated_history": new_stocks},
                         ensure_ascii=False, indent=2, default=str))
        failed = [k for k, v in report.items() if v.get("status") in ("failed", "quarantined")
                  or v.get("failed") or v.get("quarantined")]
        return 1 if failed or any(appended.values()) else 0
    finally:
        target.dispose()
        source.dispose()
        if not args.keep:
            _admin(f"DROP DATABASE IF EXISTS {SCRATCH}")


if __name__ == "__main__":
    raise SystemExit(main())
